Feature/fix newly test
aistairc/aiaccel pull request #143
Opened 2022-12-06 07:30 UTC by KanaiYuma-aist

1. create_main を引数で渡したファイルをコピーする形式に変更しました。(tests/base_test.py)

  - 今までは newly_test 内部では`subprocess.run` の実行ディレクトリ(cwd)を、`user.py` が存在するディレクトリを指定していたため、ローカル実行時に`newly_test` ディレクトリ内部に `results` ディレクトリが残っていました。
    - `newly_test` のテストはintegration test 等のように共通の `original_main.py` を使えない（パラメータ数を変えた物も含まれるため）ので、実行ディレクトリを指定する形になっていました。
  - `create_main` で `/tmp/original_main.py` にコピーするファイルを指定出来るようにし、`user.py` をコピー出来るようにして、実行ディレクトリの指定を消去することで、ローカル実行時に `results` ディレクトリが残らないようにしました。
  - 引数無しで実行した場合は、今までとほぼ同様の挙動を取ります。(コピー元が変数からファイルになっただけ)

2. テスト(newly_test以外も含む)の実行ディレクトリ(cwd)を `/tmp/work` から `/tmp` に変更しました。(tests/conftest.py)

  - 今まで `/tmp/work` を作成 -> `/tmp/work` を実行ディレクトリに指定(`os.chdir`) -> `aiaccel-start xxx --clean` を実行(`/tmp/work`を削除し、新たにもう一度生成)
    という処理を行っており、実行ディレクトリを削除した状態で `aiaccel-start xxx --clean` が実行されていました。
  - この場合、`results` ディレクトリを作成する際に、（削除済みの）実行ディレクトリに `results` を作成しようとしてエラーが発生していました。(`subprocess.run` 内部で発生していた、かつ `work` ディレクトリを出力した後のエラーだったので、テスト自体には影響はありませんでした。)
  - 上記の修正を行った際、newly_test でも同様の現象が発生することが想定されたため、併せて実行ディレクトリを削除されることのない`/tmp`にする形で修正しました。

2022-12-06 08:10 UTC, aramoto99 submitted a review, later dismissed

2022-12-11 01:13 UTC, yoshipon requested changes
ありがとうございます．newly testは英語変なので名前変えてください．
まず，このnewly testとは何をするテストでしょうか．

2022-12-12 00:27 UTC, KanaiYuma-aist commented
newly test は、端的に言えば他テストで抜けがあった項目を補完するためのテストの（仮の）総称です。
例えば、「random, tpe, nelder mead のランダム部分が違う」といったことが過去数回発生しており、このようなテストから抜けている項目を補完するためのテストです。

2022-12-12 02:28 UTC, yoshipon commented
ありがとうございます．フォルダが分かれてる理由ってありますか？ なければまとめてしまって良いと思います．

2022-12-12 02:55 UTC, KanaiYuma-aist commented
それぞれ個別のテストであることを分かりやすくする意図でフォルダ分けしていましたが、
まとめても問題ないと思います。変更しておきます。

2022-12-12 07:13 UTC, KanaiYuma-aist commented
ディレクトリ構造を変更しました。
xxxx_test_benchmark は、テスト毎に trial number や パラメータ数を変える必要があるため、分割して残しています。

2022-12-13 01:19 UTC, KanaiYuma-aist commented
issue #150 の内容と関連のあるpull requestなので、そちらの対応も同時に行おうと思います。
tempfile module を利用して改修を行う予定です。

2022-12-13 08:11 UTC, KanaiYuma-aist commented
> issue #150 の内容と関連のあるpull requestなので、そちらの対応も同時に行おうと思います。 tempfile module を利用して改修を行う予定です。

@yoshipon @aramoto99 
こちらの改修ですが、改修による差分が大量に出る見通しなので、ブランチを分けて個別でpull requestを作成したいと思います。
現状のpull requestに問題が無ければマージして頂いてもよろしいでしょうか？

2022-12-13 08:31 UTC, tkmnet commented
名前の件ですが，もし細々としたもので大きな名前をつけたり，現状のテストに直接追加することができないのであれば，supplementsとかsupplemental testsにしておいてはいかがでしょうか？

2022-12-13 08:35 UTC, KanaiYuma-aist commented
コメントありがとうございます。
supplemental tests に変更します。

2022-12-14 00:45 UTC, KanaiYuma-aist commented
他ディレクトリの命名の統一性を考えて、supplementsにディレクトリ名を変更しました。

2022-12-16 03:42 UTC, yoshipon approved these changes

2022-12-16 03:42 UTC, merged