fixed examples to match docs
aistairc/aiaccel pull request #166
Opened 2022-12-20 01:21 UTC by styamamoto

Fixed examples to match docs. 

Note:
Some files not used in the instructions were removed.
E.g., job_script_preamble.sh in the directory for instruction about local environment, or json-styled config file.

2022-12-22 13:41 UTC, yoshipon requested changes

2022-12-22 13:41 UTC, yoshipon commented on examples/benchmark/job_script_preamble.sh
> +source /path/to/optenv/bin/activate
ごめんなさい，遅くなりました．ここは，実際に実行できる (チュートリアル通り進めば通る) パスになってた方が良いと思います．

2022-12-23 00:57 UTC, styamamoto commented on examples/benchmark/job_script_preamble.sh
> +source /path/to/optenv/bin/activate
docs の方も同じ表記にしてしまったので，併せて修正します．

2022-12-23 01:08 UTC, styamamoto commented
@yoshipon 修正いたしました．確認をお願いいたします．

2022-12-23 05:51 UTC, yoshipon approved these changes

2022-12-23 05:51 UTC, yoshipon commented
ありがとうございます！

2022-12-23 05:51 UTC, merged