Add installation.md
aistairc/aiaccel pull request #167
Opened 2022-12-20 04:47 UTC by styamamoto

Added installation.md 
Instruction for MacOS is not filled.

I hope that the note environments (e.g. line 37 - 43) work well on the Read the docs.

2022-12-22 12:42 UTC, tkokada submitted a review, later dismissed
ありがとうございます．Mac向けはMacユーザーが作成すべきですね・・・

2022-12-22 13:37 UTC, yoshipon requested changes
Windowsの方ですが，実行ポリシーを変更するとセキュリティリスクが上がるので，注意書きを入れた方が良いように思います．
https://learn.microsoft.com/ja-jp/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3

2022-12-22 13:37 UTC, yoshipon commented on docs/source/installation/installation.md
> +github 経由で aiaccel をインストールする場合，[git](https://gitforwindows.org/) がインストールされている必要があります．
```suggestion
GitHub 経由で aiaccel をインストールする場合，[git](https://gitforwindows.org/) がインストールされている必要があります．
```

2022-12-22 13:37 UTC, yoshipon commented on docs/source/installation/installation.md
> +PowerShell を使用して仮想環境を作る場合，設定によっては仮想環境をアクティベートするスクリプトが実行できせん．
```suggestion
PowerShell を使用して仮想環境を作る場合，セキュリティ設定によって仮想環境をアクティベートするスクリプトが実行できないことがあります．
```

2022-12-23 00:46 UTC, styamamoto commented
@yoshipon 
- suggetion を取り入れました．
- 実行ポリシーについての注釈を付け加えました．コマンドが書いてあると，説明・注意書きを読まずに実行する人もいそうなので，「こちらを参考にして変更してください．」程度にした方が良いのではないか，とも思います．如何でしょうか？

2022-12-23 00:49 UTC, styamamoto commented
私は Mac ユーザーではないので，できれば書ける方に追記をお願いしたいです．

2022-12-23 05:52 UTC, yoshipon approved these changes

2022-12-23 05:52 UTC, yoshipon commented
ありがとうございます．良いと思います．
Mac版はいったんMac対応的なIssueに残しておくのが妥当そうです．

2022-12-26 05:02 UTC, merged