fixed job_none.log not being output
aistairc/aiaccel pull request #171
Opened 2022-12-26 08:26 UTC by KanaiYuma-aist

[resource][type]: "python_local" でaiaccel実行時に、work/log 内に job_None.log が出力される現象を修正しました。

- [resource][type]: "abci" or "local" の時、work/log 内には job_0.log, job_1.log, ... , job_(trial number).log, ... が出力されます。
  -  job_(trial number).log には、ユーザプログラムが logging モジュールを用いた際の出力を保存しています。
- これが [resource][type]: "python_local" で実行した際には、Runクラス (aiaccel.util.aiaccel) のインスタンス生成時 (Run の `__init__` 実行時)、 trial id が生成されていないため、job_None.log が出力されます。
- execute 実行時であれば、[resource][type] に依らず trial id は決定されているため、logging の設定を execute 内部に移動しました。
- また、logging の設定はプロセス内部(スレッド間)で共通のため、ユーザプログラム関数をサブスレッドで実行していると、loggingの出力が全て同じファイルに出力される(例えば、job_0.logに全て出力される)ため、ユーザプログラム関数をサブプロセス(multiprocessing)で実行するように変更しました。

2023-01-12 10:55 UTC, yoshipon commented
これってmultiprocessingで管理するべきなのでしょうか．
@aramoto99 @tkokada ご意見いただけると幸いです．

2023-01-13 00:51 UTC, KanaiYuma-aist commented
ユーザプログラムのlogging 出力をjob_(trial number).logに個別に出力しなければ、multiprocessingにする必要は無いと思います。
1つのファイルに重複して出力させると、ユーザプログラムのlogging出力が多い場合に（恐らく書き込みの待機時間で）処理時間が多くなるため、完全に出力しないようにするか、multiprocessingにして個別に出力するようにするか
どちらかになると思われます。
（あるいはサブスレッド毎にrootのlogging出力を個別に受け取る方法があれば、そちらでも大丈夫かと思われます。）

また、local, abci はユーザプログラムをマルチプロセスで実行しているのに対し、python_local はマルチスレッドで実行されているため
統一性を持たせる意味もあったと記憶しています。

ユーザプログラム実行箇所
local
https://github.com/aistairc/aiaccel/blob/392d1634b3b761e737cfcbca38507b668d7ab129/aiaccel/scheduler/job/model/local_model.py#L31
abci
https://github.com/aistairc/aiaccel/blob/392d1634b3b761e737cfcbca38507b668d7ab129/aiaccel/scheduler/job/model/abci_model.py#L52
（exec_runnerはコマンドrunner_command をサブプロセスで実行する関数）
python_local
https://github.com/aistairc/aiaccel/blob/392d1634b3b761e737cfcbca38507b668d7ab129/aiaccel/scheduler/pylocal_scheduler.py#L59

2023-01-13 01:04 UTC, yoshipon commented
ありがとうございます．python_localは高速化のためのモードなので，遅くなる仕組みの導入には慎重になった方が良いと思います．
multiprocessing使うならPool (プロセスプール) でできますか？

2023-01-13 01:09 UTC, KanaiYuma-aist commented
> multiprocessing使うならPool (プロセスプール) でできますか？
試してみます。

2023-01-13 07:09 UTC, KanaiYuma-aist commented
まだ調査段階ですが、Pool.map() を用いてユーザプログラムを実行しようとすると、下記のようなエラーが発生します。
挙動から推測すると、シリアライズ不可の変数を削除する処理 __getstate__ が、Pool.map() 実行時に呼び出されて、storage 変数が削除されている様子です。
（storage 以外の __getstate__ で削除されている変数を参照しようとすると、同様のエラーが起きました。）

```
$ aiaccel-start --config config.yaml --clean
Cleaning workspace
Workspace directory /home/member/hpopt/fix_pylocal_log/aiaccel/examples/benchmark/work is cleaned.
config: /home/member/hpopt/fix_pylocal_log/aiaccel/examples/benchmark/config.yaml
Optimizer DEBUG    create numpy random generator by seed: 42
Scheduler DEBUG    create numpy random generator by seed: 42
Master    INFO     0/20 finished, ready: 0 ,running: 0, end estimated time: Unknown
Optimizer INFO     hp_ready: 0, hp_running: 0, hp_finished: 0, total: 20, pool_size: 4
Optimizer INFO     0/20, finished, ready: 0, running: 0
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/member/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/member/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/member/hpopt/fix_pylocal_log/work/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/scheduler/pylocal_scheduler.py", line 77, in execute
    self.storage.trial.set_any_trial_state(trial_id=trial_id, state='running')
AttributeError: 'PylocalScheduler' object has no attribute 'storage'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/member/hpopt/fix_pylocal_log/work/bin/aiaccel-start", line 11, in <module>
    load_entry_point('aiaccel==0.0.1', 'console_scripts', 'aiaccel-start')()
  File "/home/member/hpopt/fix_pylocal_log/work/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/cli/start.py", line 69, in main
    if not module.inner_loop_main_process():
  File "/home/member/hpopt/fix_pylocal_log/work/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/scheduler/pylocal_scheduler.py", line 62, in inner_loop_main_process
    self.pool.map(self.execute, [trial_id])
  File "/home/member/anaconda3/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/member/anaconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: 'PylocalScheduler' object has no attribute 'storage'
```

2023-01-18 06:45 UTC, KanaiYuma-aist commented
Pool (プロセスプール) を利用する形で改修しました。

- `pool.map(self.run.execute, ...)` で実装しようとしたのですが、`self.run` がpickle不可の変数だったため、エラーが発生し断念しました。
- なので、pickle化によって削除される変数を、Pool で実行する際に再定義する形で実装しました。
  - `self.num_node <= 1`(直列実行) の時は、従来通り直接 `self.execute(trial_id)` を実行します。
  - `self.num_node > 1`(並列実行)の時は、`self.pool.map(self.execute_wrapper, trial_ids)` でまとめて実行します。

2023-01-18 06:54 UTC, yoshipon commented
なるほどです．ユーザから指定された関数が，`xxx_func` だったとして， `pool.map(xxx_func, ...)` とすれば回避できそうですが，どうでしょうか．

2023-01-18 07:29 UTC, KanaiYuma-aist commented
単純に `pool.map(self.user_func, ...)` (`self.user_func` がユーザプログラムに該当) が実行出来るか確認した所、`_pickle.PicklingError` が発生しました。
`self.user_func` 自体も pickle不可の変数(動的importを行っている都合と推測)のようなので、簡単には出来ないのではないかと思われます。

2023-02-07 10:57 UTC, yoshipon commented
コード確認しました．ありがとうございます．
`execute_wrapper` を `Pool.map` されてるようですが，この実装だと毎回 `execute_wrapper` 内でDBの初期化が走りませんか？
オーバーヘッドが大きすぎると思います．

元のthreading版と比べて，CPU使用率と処理時間はどう変化していますでしょうか．
ご確認お願いします．

2023-02-08 00:57 UTC, KanaiYuma-aist commented
ひとまず処理時間の方を先に確認しました。
example/benchmarkを用いて、
num_node: 100
search_algorithm: "aiaccel.optimizer.RandomOptimizer"
trial_number: 1000
で実行して、
threading版(mainブランチ): Total time [s] : 137
pool版: Total time [s] : 113
でした。
実行に用いたファイル
[benchmark.tar.gz](https://github.com/aistairc/aiaccel/files/10680628/benchmark.tar.gz)

CPU使用率はこれから調査します。

2023-02-08 02:31 UTC, KanaiYuma-aist commented
cpu使用率はpoolがthreadの2~3倍程度増えていました。
（実行条件は処理時間確認の方と同様）

![cpu_usage_graph](https://user-images.githubusercontent.com/105629713/217413360-72514580-9674-467e-974a-74cae96bc41e.png)

（vmstatコマンドで調査しました
　[vmstat_pool.log](https://github.com/aistairc/aiaccel/files/10681099/vmstat_pool.log)
　[vmstat_thread.log](https://github.com/aistairc/aiaccel/files/10681100/vmstat_thread.log)）

2023-02-08 05:41 UTC, yoshipon commented
ありがとうございます。であれば、やはり改修が必要に思います。
`pool.map(self.user_func, ...)` がPickleできない問題で動かないとのことですが、`user_func_wrapper` は `pool.map` できるのであれば、`self.user_func`もPickleできるように思います。
どのようなエラーだったのでしょうか。

よろしくお願いします。

2023-02-08 05:43 UTC, yoshipon commented
よければ、`benchmark.tar.gz` の実行の仕方を教えてください。

2023-02-08 05:48 UTC, KanaiYuma-aist commented
> よければ、benchmark.tar.gz の実行の仕方を教えてください。

aiaccel/example 内のbenchmark を benchmark.tar.gz で置き換えれば実行出来ると思います。

> どのようなエラーだったのでしょうか。

self.user_func を直接 pool で実行しようとすると、self.user_func 自体がpickle化不可のためエラーが発生していました。
poolする関数内でself.user_func を再定義すれば実行可能です。

丁度、execute_wrapper 内でself.user_funcのみを再定義し、storage関連処理をpool外部に移動させた改善版をアップロードしました。

2023-02-08 05:52 UTC, KanaiYuma-aist commented
cast_y, set_logging_basicConfig は aiaccel/scheduler/pylocal_scheduler.py 内から直接参照出来る方が都合が良かった(Runクラスはpickle不可でpool内部から参照出来ない)ので、
aiaccel/util/aiaccel.py の構成を一部変更しました。

関数名やcast_y, set_logging_basicConfigの定義箇所については、もっと良いものがあるかもしれません。

2023-02-08 05:56 UTC, KanaiYuma-aist commented
実行時間は Total time [s] : 113 -> Total time [s] : 104 に、
cpu使用率は以下のように改善されました。
![cpu_usage_graph](https://user-images.githubusercontent.com/105629713/217446776-4b3ab09f-c31e-4402-a8a4-a473a937c174.png)

2023-02-08 06:07 UTC, yoshipon requested changes
ありがとうございます。やはり、user_funcを実行するだけにしてはコストが高い処理が多い気がします。
レビューしましたので修正をお願いします。

2023-02-08 06:07 UTC, yoshipon commented on aiaccel/scheduler/pylocal_scheduler.py
> +            for trial_id, (xs, y, err, start_time, end_time) in zip(trial_ids, results):
```suggestion
            for trial_id, (xs, y, err, start_time, end_time) in zip(
                trial_ids,
                self.pool.map(self.execute_wrapper, args)
            ):
```

また、mapだと同期実行されてしまうので、imap_unordered使うように修正お願いします。

2023-02-08 06:07 UTC, yoshipon commented on aiaccel/scheduler/pylocal_scheduler.py
> +        return xs, y, err
Config(self.config_path) するのを避けて頂けますか？
毎回ファイルアクセスが実行されており、非効率だと思います。

https://docs.python.org/ja/3/library/multiprocessing.html#multiprocessing.pool.Pool
にあるように`initializer`を指定すれば良いものと思います。

これらの機能は、メソッドにするのでなく、クラスの外の関数として定義してください。
メソッドにしてしまうと、バインドしているインスタンスをPickle化する必要が生じます。

2023-02-08 07:51 UTC, KanaiYuma-aist commented on aiaccel/scheduler/pylocal_scheduler.py
> +            for trial_id, (xs, y, err, start_time, end_time) in zip(trial_ids, results):
レビューありがとうございます。
imap_unordered を使う形で改修しました。
https://github.com/aistairc/aiaccel/blob/92fb2e1187d05ee9b5efb5f9e87a6d1a3ae0ed5b/aiaccel/scheduler/pylocal_scheduler.py#L56-L59

2023-02-08 07:54 UTC, KanaiYuma-aist commented on aiaccel/scheduler/pylocal_scheduler.py
> +        return xs, y, err
`config`, `user_func` の再定義を `initilizer` で行う形に改修しました。
`initilizer` で参照する都合で、`get_callable_object` の定義もクラス外に移動しました。
https://github.com/aistairc/aiaccel/blob/92fb2e1187d05ee9b5efb5f9e87a6d1a3ae0ed5b/aiaccel/scheduler/pylocal_scheduler.py#L114-L121

2023-02-08 08:01 UTC, KanaiYuma-aist commented
レビューありがとうございます。
レビュー結果の反映を行いました。

反映後の実行時間は Total time [s] : 105
cpu使用率は以下の通りです。
![cpu_usage_graph](https://user-images.githubusercontent.com/105629713/217469201-aa02bc5b-4617-487b-a328-a243c600f07a.png)

vmstat結果
[vmstat_pool_improve2.log](https://github.com/aistairc/aiaccel/files/10683166/vmstat_pool_improve2.log)

2023-02-09 05:25 UTC, yoshipon requested changes

2023-02-09 05:25 UTC, yoshipon commented on aiaccel/scheduler/pylocal_scheduler.py
> +    return getattr(module, attr_name)
executeてexecute_wrapperでパスが全く違う (前者はself.user_funcを使い、後者はグローバル変数) なのが良くないように感じます。
メンテ性を考えて、出来るだけ処理を共通化して貰えますか？

2023-02-09 05:25 UTC, yoshipon commented on aiaccel/util/aiaccel.py
> +def set_logging_basicConfig(workspace, trial_id):
この関数名はもう少し考えたいですね。妙案ありますでしょうか。

2023-02-09 06:04 UTC, KanaiYuma-aist commented on aiaccel/scheduler/pylocal_scheduler.py
> +    return getattr(module, attr_name)
現状、num_node = 1 の時（直列実行）は、 `self.user_func` を用いてユーザ関数を実行して、
num_node > 1 の時（並列実行）は、pool を使う都合で `initilizer`内でグローバル変数にユーザ関数を定義しています。

クラス外の `initilizer` を経由する都合で `self.user_func` で統一するのは難しそうなので、
num_node = 1 の時も pool を用いる（`Pool(1)`で実行する）方向で統一しようと思いますが、よろしいでしょうか？

> 他で使いまわしてないなら、1つに纏めて良いかと。(get_callable_object)

num_node = 1 の時は、`self.user_func` を直接呼び出す都合で `__init__ `内部でも `get_callable_object` を呼び出しています。
上の方針で統一すれば、 `initilizer` にまとめて問題無いかと思われます。

2023-02-09 06:18 UTC, yoshipon commented on aiaccel/scheduler/pylocal_scheduler.py
> +    return getattr(module, attr_name)
ありがとうございます。難しいところですが、その方針でお願いします。
num_node=1の時は、multiprocessing.pool.Poolでなく、multiprocessing.pool.ThreadPool を使うようにして貰えますか？
この場合はオーバーヘッドはありますが、フォークしないので多少ましだと思います。

よろしくお願いします。

2023-02-09 07:55 UTC, KanaiYuma-aist commented on aiaccel/scheduler/pylocal_scheduler.py
> +        return xs, y, err
確かにそうですね。反映しました。
d34f97542ff1ed0f3a83aca37aeb80fd43533aa2

2023-02-09 08:03 UTC, KanaiYuma-aist commented on aiaccel/scheduler/pylocal_scheduler.py
> +    return getattr(module, attr_name)
反映しました。
de05652a48d5feddda9b856d292af02218d94895

なお、example/bechumark を trial_number: 1000 num_node: 1 で実行した所
実行時間は
反映前 Total time[s]: 150 -> 反映後 Total time [s] : 120
に変化し、cpu使用率は以下のようになりました。
![cpu_usage_graph](https://user-images.githubusercontent.com/105629713/217752493-c3cd3418-db7b-4845-84fc-279ca4350b09.png)
反映前 [vmstat_serial.log](https://github.com/aistairc/aiaccel/files/10694720/vmstat_serial.log)
反映後 [vmstat_serial_ThreadPool.log](https://github.com/aistairc/aiaccel/files/10694721/vmstat_serial_ThreadPool.log)

2023-02-09 08:05 UTC, KanaiYuma-aist commented on aiaccel/util/aiaccel.py
> +def cast_y(
aiaccel/util/cast.py を作成し、そこに cast_y を移動させました。
621f77aaaf6ee1a5a3d8077bb378c7c253a0c4a6

2023-02-09 08:06 UTC, KanaiYuma-aist commented on aiaccel/util/aiaccel.py
> +def set_logging_basicConfig(workspace, trial_id):
`set_logging_file_for_trial_id` に変更してみました。
2299eaed49232455281a51c5336fa400212d3abf f9f5dd0a498e3e983a34dfa1d5fe2ced1965fb3b

2023-02-13 02:04 UTC, yoshipon requested changes

2023-02-13 02:04 UTC, yoshipon commented on aiaccel/scheduler/pylocal_scheduler.py
> +            self.com.out(objective_y=y, objective_err=err)
この部分って、 `self.execute` 内で実行するとまずいですか？ initializeはグローバル関数なのに、executeがメソッドなのが気になっています。
@aramoto99 さんに伺った方がよいでしょうか。今日議論できると幸いです。

2023-02-13 05:46 UTC, yoshipon requested changes

2023-02-13 05:46 UTC, yoshipon commented on aiaccel/scheduler/pylocal_scheduler.py
> +            self.pool = ThreadPool(self.num_node, initializer=initializer, initargs=(self.config_path,))
```suggestion
        Pool_ = Pool if self.num_node > 1 else ThreadPool
        self.pool = Pool_(self.num_node, initializer=initializer, initargs=(self.config_path,))
```

2023-02-13 05:46 UTC, yoshipon commented on aiaccel/scheduler/pylocal_scheduler.py
> +            err = str(e)
```suggestion
        try:
            y = cast_y(user_func(xs), y_data_type=None)
        except BaseException as e:
            err = str(e)
            y = None
        else:
            err = ""
```

2023-02-13 05:46 UTC, yoshipon commented on aiaccel/scheduler/pylocal_scheduler.py
> +        err = ""
```suggestion
```

2023-02-13 06:21 UTC, KanaiYuma-aist commented on aiaccel/scheduler/pylocal_scheduler.py
> +            err = str(e)
これと↓に関してはaiaccel/util/aiaccel.py も同様の書き方になっているため、aiaccel.pyのコードも同様に修正しようと思います。

2023-02-14 04:37 UTC, yoshipon approved these changes

2023-02-14 04:37 UTC, yoshipon commented
ご対応ありがとうございました。

2023-02-14 05:09 UTC, merged