Develop/database fix test
aistairc/aiaccel pull request #18
Opened 2022-07-20 07:13 UTC by KanaiYuma-aist

2022-07-20 07:24 UTC, aramoto99 commented on aiaccel/util/process.py
> +    for pInfoDict in psutil.process_iter(['pid', 'username', 'status', 'create_time', 'cmdline']):
Might it be better to lowercase it to match the rest of the description?
pInfoDict -> p_info

2022-07-20 07:31 UTC, KanaiYuma-aist commented
https://github.com/aistairc/aiaccel/pull/18#issuecomment-1189921856

add comment to https://github.com/aistairc/aiaccel/pull/18#issue-1310556168

2022-07-22 01:30 UTC, aramoto99 requested changes

2022-07-22 01:48 UTC, KanaiYuma-aist commented on aiaccel/storage/hp/fs.py
> +            if hp is not None:
When running tests in `tests/unit/storage/fs/test_fs_hp.py`, `storage.hp.set_any_trial_param` would store None in the array and an error would occur trying to execute `(None).remove()`. 
So add `if hp is not None:`.

---

tests/unit/storage/fs/test_fs_hp.py のテスト実行時に
`storage.hp.set_any_trial_param` によって配列に None が格納され、
`(None).remove()` を実行しようとしてエラーが発生していたため、
`if hp is not None:` を追加しました。

https://github.com/aistairc/aiaccel/blob/7c0a3aaeecc8f8be3c87a80a5704d6f3f950e115/tests/unit/storage/fs/test_fs_hp.py#L97-L115

2022-07-22 01:56 UTC, yoshipon commented on aiaccel/storage/hp/fs.py
> +            if hp is not None:
So, is it an intended behavior that the items in `self.datas.data` can become `None`...?

2022-07-22 02:10 UTC, KanaiYuma-aist commented on aiaccel/storage/hp/fs.py
> +            if hp is not None:
> (Perhaps the next two items need to be corrected as well).

I changed trial_id to 3 in the test code `tests/unit/storage/fs/test_fs_timestamp.py` `tests/unit/storage/fs/test_fs_error.py` which calls those processes, and the same error occurred.

So I think it is necessary to add `if hp is not None:` as well.

---

> （以下のコードにも似たような処理があります．変更すべきですか？）

試しにそれらの処理を呼び出しているテストコード
`tests/unit/storage/fs/test_fs_timestamp.py`
`tests/unit/storage/fs/test_fs_error.py`
の trial_id に当たる部分を 3 などに変更してテストした所、
同様のエラーが発生しました。

なので、同様に`if hp is not None:`の追加が必要だと思われます。

2022-07-22 04:55 UTC, aramoto99 approved these changes

2022-07-22 05:56 UTC, merged