fix sphinx errors
aistairc/aiaccel pull request #184
Opened 2023-01-16 00:50 UTC by styamamoto

Fixed sphinx errors but this work is WIP.

Some warnings are still remain because;
- `__init__.py` is not defined correctly.  [#182](https://github.com/aistairc/aiaccel/issues/182)
- Equations in `developer_guide/custom_optimizer.md`
 is not rendered correctly as html.
- I couldn't remove `WARNING: Definition list ends without a blank line; unexpected unindent.` arise from docstring of `aiaccel.config.BaseConfig.get_property`.

2023-01-17 08:16 UTC, styamamoto commented
All of warnings and errors on docs-building are removed.
Note, some of extention and configurations are added to docs/source/conf.py.

2023-01-18 06:57 UTC, yoshipon requested changes
気になっていた不備がキレイになってて助かります．

2023-01-18 06:57 UTC, yoshipon commented on aiaccel/config.py
> +    Fork by confile: https://github.com/777nancy/confile
これは残しておいた方が良いかと．多分まだconfileだった自体の名残があるってことですよね？ あれ違う…？

2023-01-18 07:07 UTC, styamamoto commented on aiaccel/config.py
> +    Fork by confile: https://github.com/777nancy/confile
比較のページだとちょっとわかりづらいですが，文章自体は残っています．
(文の順番は入れ替わっていますが)

https://github.com/aistairc/aiaccel/blob/0dbbc6df0daae03988c2c7cc7ae33a70c6340835/aiaccel/config.py#L20-L24

2023-01-23 05:01 UTC, yoshipon approved these changes

2023-01-23 05:01 UTC, merged