Added Japanese Contribution Guide
aistairc/aiaccel pull request #188
Opened 2023-01-23 06:45 UTC by styamamoto

mtg の内容を反映し，コントリビューションガイドを更新しました．

以下の内容は今後追加が必要な内容です．
- linter, auto formatter の指定・テストへの組み込み
- GitHub actions のテストのローカル実行法
- 英文/和文 のドキュメントのローカルビルド法

2023-01-25 06:48 UTC, styamamoto commented on docs/source/contribution_guide/contribution_guide.md
> +
以下の２つを追加すれば現状の Github actions と等価なテストになるでしょうか？
https://github.com/aistairc/aiaccel/blob/5f270d2e378050e04698e6d996e3bfe19a476673/.github/workflows/actions.yaml#L32-L37

2023-01-27 05:24 UTC, 3bisuoka commented on docs/source/contribution_guide/contribution_guide.md
> +
ちょうど引用で抜き出している箇所の35行目のFlack8はFlake8のtypoですか？

2023-01-27 07:43 UTC, tkokada commented on docs/source/contribution_guide/contribution_guide.md
> +
GitHub Actionsで実行しているpytest全てを指していますが，長いですね・・・

https://github.com/aistairc/aiaccel/blob/5f270d2e378050e04698e6d996e3bfe19a476673/.github/workflows/actions.yaml#L29-L61

2023-02-03 05:29 UTC, yoshipon commented
@tkokada @aramoto99 @KanaiYuma-aist こちら如何でしょうか．
問題なければapproveして頂けると幸いです．何か懸念点あれば，議題上げて頂けると幸いです．

よろしくお願いします．

2023-02-04 07:48 UTC, yoshipon approved these changes
ありがとうございます！ レビューしましたので，確認・修正お願い致します．

2023-02-04 07:48 UTC, yoshipon commented on docs/source/contribution_guide/contribution_guide.md
> +バグの報告を行う際には，以下の内容についての明確かつ簡潔な説明を含めることを推奨します．
```suggestion
バグの報告では，以下の内容についての明確かつ簡潔な説明を含めてください．
```

2023-02-04 07:48 UTC, yoshipon commented on docs/source/contribution_guide/contribution_guide.md
> +問題を発見した場合や，機能のリクエストがあった場合，まずリポジトリにある既存のイシューを確認してください．
```suggestion
問題を発見した場合や追加機能の要望がある場合，すでに同様のイシューが投稿されていないか確認をお願いします．
```

2023-02-04 07:48 UTC, yoshipon commented on docs/source/contribution_guide/contribution_guide.md
> +コードの実装が必要であると判断された場合，コードの作成を行います．
```suggestion
aiaccelのコードを修正しリポジトリに反映して欲しい場合，プルリクエストを実行してください．
```

2023-02-04 07:48 UTC, yoshipon commented on docs/source/contribution_guide/contribution_guide.md
> +- フォークした後，aiaccel をダウンロードし，インストールします．
```suggestion
- フォークした後，aiaccel のリポジトリをcloneします．
```
(インストールまで行う必要がある場合，適宜修正をお願いします．

2023-02-04 07:48 UTC, yoshipon commented on docs/source/contribution_guide/contribution_guide.md
> +
```suggestion

```

2023-02-04 07:48 UTC, yoshipon commented on docs/source/contribution_guide/contribution_guide.md
> +- 大規模な追加の場合，例 (docs/source/examples) やモジュールレベルの説明はあるか？
これは事前にイシュー等で他の開発者と議論したか？
みたいな文面が欲しいですね．

2023-02-04 07:48 UTC, yoshipon commented on docs/source/contribution_guide/contribution_guide.md
> +- プルリクエストに関係する issues がある場合，クロスリファレンスを付けることが可能です．
これは要望として書いてください．Closes #N ついてないと閉じるの大変なので．
ここだけissuesになってるので，イシュー？
それとも全部Issueにします？ GitHubは日本語版がないので，Issue / Pull Requestでも良い気がしています．

2023-02-04 07:48 UTC, yoshipon commented on docs/source/contribution_guide/contribution_guide.md
> +### Docstrings
```suggestion
## Docstrings
```
こうで良い気がします．

2023-02-06 05:47 UTC, tkokada commented on docs/source/contribution_guide/contribution_guide.md
> +    - iaccel/tests/unit 以下のディレクトリ構造は，config.py などの一部のモジュールを除いて，aiaccel/aiaccel 以下の構造に対応します． 例えば，aiaccel/aiaccel/optimizer/abstract_optimizer.py のテストは aiaccel/tests/unit/optimzier_test/test_abstract_o
- iaaccel -> aiaccel

2023-02-06 05:56 UTC, tkokada commented on docs/source/contribution_guide/contribution_guide.md
> +
- APIリファレンスの生成
  - sphinx-apidoc -f -o docs/source/api_reference aiaccel
- 多言語ドキュメントの生成
  - cd docs
  - make gettext
  - sphinx-intl update -p build-gettext -l en -l ja

2023-02-06 06:03 UTC, tkokada requested changes
遅くなりましたがざっと見ました．
以下が追加されれば問題ないと思います．

- ドキュメントについて，APIリファレンスの生成方法とi18n(en, jpだけですが)の生成方法を追加
- pycodestyle, flake8のテスト方法の追加

2023-02-06 09:18 UTC, styamamoto commented on docs/source/contribution_guide/contribution_guide.md
> +
ありがとうございます．
一応確認ですが，最後のコマンドは `sphinx-intl update -p build/gettext -l en -l ja` でしょうか？ (-p の後ろのパスの部分)

2023-02-06 09:22 UTC, styamamoto commented
みなさま，コメントありがとうございます．
反映させていただきました．

(補足)
API リファレンスに生成できないものがありましたが，
\_\_init\_\_.py がパッケージに無いことが原因のようです．
(インポートの挙動含めて，別イシューで対応します．)

2023-02-06 09:28 UTC, styamamoto commented
こちらの確認不足ではあるのですが，
flake8 のバージョンが最新だったせいで全てのコードが Failed になってしまい焦りました．

テストの実行の項目に何か注釈を付けても良いかと思いましたが，如何でしょうか？

2023-02-07 10:59 UTC, yoshipon commented
@styamamoto ありがとうございます．確かに… お願いできますか？
これ，コード側の修正で対応したいところですね．

2023-02-08 05:58 UTC, styamamoto commented
GitHub Actions が変更になったので，スタイルチェックの説明を書き直しました．
flake8 のバージョン指定は外したので，追加コメントはしていません．

https://github.com/aistairc/aiaccel/blob/8d2d1611baa1c5a85b6bc7c64c21d03613de7873/docs/source/contribution_guide/contribution_guide.md?plain=1#L142-L156

2023-02-08 06:29 UTC, yoshipon commented on docs/source/contribution_guide/contribution_guide.md
> +
@tkokada こちらいかがでしょう…？

,この部分反映できればマージしたいと思います。

2023-02-13 07:47 UTC, yoshipon commented
@tkokada すみません、こちら、changes requestedにされてるようなので、問題なければapproveして頂けると幸いです。

2023-02-14 05:29 UTC, merged