Implement multi-objective TPE using optuna.
aistairc/aiaccel pull request #195
Opened 2023-01-30 03:45 UTC by tkokada

- 概要
  - optunaのMOTPEオプティマイザの追加
- MOTPEの使い方
  - ユーザープログラムは，多目的最適化に合わせ list で値を返すこと
  - コンフィグレーションファイルの goal には list で値を与えること
  - 当然だが，ユーザープログラムの戻り値とコンフィグレーションファイルの goal の list は同じ長さとすること．
- 変更点
  - 多目的最適化であるか？という比較（上述のコンフィグレーションファイルの goal が list という条件を使用）を多数の箇所に追加．
  - MOTPEのパレートフロントは複数あるので，他のオプティマイザが持つ一意な最適解が無い．aiaccelのMOTPEオプティマイザもこれに倣い最適解を返さない．今後パレートフロントのハイパーパラメータを保持しておくべきとする場合，別途データベースに保存する実装を行う．
  - 前述と同じく verification も実行しない．
  - requirements.txtに optuna 3.1.0 を記載．
  - MOTPEに関するテスト群の追加．
- 課題
  - MOTPEの状態はoptunaが管理するため，optunaのデータベースを保存しておかない場合，ユーザーとしては結果しか知ることができない．
  - 前述に伴い，解の優劣もaiaccelの結果からはわからない．
  - 上記２点から，aiaccelの結果としてoptunaのデータベースを保存し（一応これで後述の件を内包している），パレートフロントをaiaccelのデータベースに保存する実装を追加するか．要検討．

2023-02-01 01:13 UTC, aramoto99 commented on aiaccel/optimizer/__init__.py
> +    MOTpeOptimizer,
__all__に関して，https://github.com/aistairc/aiaccel/issues/182 に合わせたほうが良いかと思いましたが，いかがでしょうか？

2023-02-02 13:13 UTC, yoshipon commented on aiaccel/optimizer/__init__.py
> +    MOTpeOptimizer,
mypy?通らないそうなので，お願いします．

2023-02-03 07:29 UTC, tkokada commented on aiaccel/optimizer/__init__.py
> +    MOTpeOptimizer,
承知しました！

2023-02-13 02:14 UTC, yoshipon requested changes

2023-02-13 02:14 UTC, yoshipon commented on aiaccel/master/abstract_master.py
> +            evaluator.save()
この部分ですが、ロジックが見えづらいのが少しきになりました。こういうのどうでしょうか？
```
        if isinstance(self.goal, list):
            self.logger.info('Multi-objective optimization does not run an evaluation process.')
        if isinstance(self.goal, str):
            if self.goal.lower() == aiaccel.goal_maximize:
                evaluator = MaximizeEvaluator(self.options)
            elif self.goal.lower() == aiaccel.goal_minimize:
                evaluator = MinimizeEvaluator(self.options)
                
            evaluator.evaluate()
            evaluator.print()
            evaluator.save()
        else:
            error_message = f'Invalid goal: {self.goal}.'

            self.logger.error(error_message)
            raise ValueError(error_message)
```

2023-02-13 02:14 UTC, yoshipon commented on aiaccel/optimizer/tpe_optimizer.py
> +        storage_path = str(f"sqlite:///{self.ws}/optuna-{self.study_name}.db")
細かいですが、これはstrになってるのでキャスト不要かと思います。
```suggestion
        storage_path = f"sqlite:///{self.ws}/optuna-{self.study_name}.db"
```

2023-02-13 02:16 UTC, yoshipon commented on aiaccel/master/abstract_master.py
> +            evaluator.save()
と、思ったんですが、これだと、`isinstance(self.goal, str)` かつ `self.goal.lower()` がminでもmaxでもないときに落ちますね…

2023-02-13 02:18 UTC, yoshipon commented on aiaccel/master/abstract_master.py
> +            evaluator.save()
こうか？ とも思ったんですが、これはこれでキモイですね。
```
        if isinstance(self.goal, list):
            self.logger.info('Multi-objective optimization does not run an evaluation process.')
        else:
            if self.goal.lower() == aiaccel.goal_maximize:
                evaluator = MaximizeEvaluator(self.options)
            elif self.goal.lower() == aiaccel.goal_minimize:
                evaluator = MinimizeEvaluator(self.options)    
            else:
                error_message = f'Invalid goal: {self.goal}.'

                self.logger.error(error_message)
                raise ValueError(error_message)

            evaluator.evaluate()
            evaluator.print()
            evaluator.save()
```

2023-02-13 02:19 UTC, yoshipon commented on aiaccel/master/abstract_master.py
> +            evaluator.save()
```
        if not isinstance(self.goal, list):  # single objective mode
```
みたいな注釈入れるのでどうでしょうか…？

2023-02-13 04:59 UTC, tkokada commented on aiaccel/master/abstract_master.py
> +            evaluator.save()
ありがとうございます．メソッドにしたら良いかもしれないと思いました．

```
if is_multi_objective():
```

2023-02-13 04:59 UTC, tkokada commented on aiaccel/optimizer/tpe_optimizer.py
> +        storage_path = str(f"sqlite:///{self.ws}/optuna-{self.study_name}.db")
本当ですね．直しておきます！

2023-03-19 10:19 UTC, yoshipon submitted a review, later dismissed

2023-03-19 10:35 UTC, yoshipon commented
お疲れ様です．マージ解消しました．多分問題ないと思いますが，念のためご確認頂けると幸いです．

2023-03-20 09:19 UTC, merged

2023-03-22 05:34 UTC, styamamoto commented
テストの以下の箇所で警告が出ているみたいです．
motpe で最適化する際の objective は list 形式と認識しているのですが，
モックの返り値 (`return_value=1` の部分) を list 等に直した方が安心かと思います．

https://github.com/aistairc/aiaccel/blob/3e752cac51c8d103587b13f3240b1f05154da75e/tests/unit/optimizer_test/test_motpe_search.py#L39-L40

2023-03-22 05:54 UTC, yoshipon commented
あざます．CIでエラー出てなかったので大丈夫かと思ってました…
ぱっと直せます…？

2023-03-22 06:27 UTC, styamamoto commented
PR #253 で修正いたします．