Command line arguments available
aistairc/aiaccel pull request #206
Opened 2023-02-07 08:43 UTC by aramoto99

user.pyを単体で実行する際，ハイパーパラメータ値をコマンドライン引数から指定できるように変更しました．
（従来通り，database を参照してハイパーパラメータの値を取得することも可能）

<hr>
例

- user.py
~~~ python
from aiaccel.util import aiaccel
import time

def main(p):
    y = (p["x1"]**2) - (4.0 * p["x1"]) + (p["x2"]**2) - p["x2"] - (p["x1"] * p["x2"])
    
    return y

if __name__ == "__main__":
    run = aiaccel.Run()
    run.execute_and_report(main)
~~~

- user.py 単体実行の例
1. コマンドライン引数からハイパーパラメータ値を指定する場合の例 
この場合，`x1`，`x2`のデータ型は`float`です．
~~~ bash
python user.py --x1 0.01 --x2 0.9
~~~

2. (従来の実行方法) database を使用する場合の例. 演算済みのハイパーパラメータ値が database に格納されている状態でのみ使用可能
~~~ bash
python user.py --trial_id 1 --config config.yaml --use_db
~~~

2023-02-08 07:47 UTC, styamamoto commented
ありがとうございます．
現状だと `use_db` のオプションは常に `True` になっているのでしょうか？

2023-02-08 08:24 UTC, aramoto99 commented
`use_db`のデフォルトは`False`です．

2023-02-09 01:47 UTC, yoshipon commented
@aramoto99 ありがとうございます。これって、出力は必ずDBに書き込まないといけない感じでしょうか？
昔のFS版だと、プログラムは引数でハイパラを取って、結果はファイルだか標準出力に吐くだけだったと思うんですが、そういう実装にできますでしょうか。

2023-02-09 02:08 UTC, aramoto99 commented
> 出力は必ずDBに書き込まないといけない感じでしょうか？
- aiaccelからuser.pyを呼出す場合，最終結果をDBに書き込みます．
- aiaccelを使用しない場合(user.pyを単体で実行する場合)は，標準出力に結果を出力します（DBにはアクセスしない）
この場合はDB機能を完全に切り離しています．

2023-02-09 02:31 UTC, styamamoto commented
ユーザープログラムのラッパーを廃止できるような改修が良いのではないかと，思っていたのですが
実装の可否や aiaccel の目指すところと照らして如何でしょうか？

- コンフィグの job_command にはユーザーが持っているプログラムの実行コマンドを書く．
- ユーザープログラムはコマンド引数としてパラメータなど受け取り，標準出力に計算結果を返す．
- util.process.OutputHandler などが出力を確認して DB に結果やエラーを書き込む．

というようなイメージです．

設定ファイルやユーザープログラムは以下のような感じです．

```yaml
# config.yaml
generic:
    job_command: sh user.sh
```
```sh
# user.sh
trial_id=$1
x1=$2
x2=$3

y=$(($x1+$x2))

echo trial_id:$trial_id, objective:$y
```
use.sh を単体で実行すると以下のようになります．
```bash
$ sh user.sh 1 2 3
echo trial_id:1, objective:5
```

この提案は，python を書かない (書けない) 人が aiaccel を使うかも，という前提に立っているので，
wrapper.py という python のファイルを編集させずに使えるようにしたい，という意図があります．
(この前提については，私の解釈違いかもしれないですが...)

また，aiaccel.util.aiaccel.Run はあくまで python 関数のラッパーという立ち位置にして，
- python を書く (書ける) 人が持っている `objective()` という関数にコマンドラインパーサの機能を追加する
- リターン値を標準出力にプリントさせる機能を追加する

という役割のみを持たせると（デコレータ？），aiaccel が job_command を実行した際にの動作が統一されて良いのではないでしょうか．

2023-02-09 02:35 UTC, yoshipon commented
お二人ともありがとうございます。私もuser.shのような、ラッパーを廃止できる枠組みを考えていました。
初期のaiaccelではそういう実装じゃないでしたっけ？

上の例でいうと
```bash
echo $y
```
で十分だと思いますが、他のC++やFortran、bashのソフトウェアをそのまま叩けるような実装を想定していました。

2023-02-09 02:58 UTC, aramoto99 commented
@yoshipon @styamamoto 
ご意見ありがとうございます，そのように改修致します．

2023-02-28 08:04 UTC, aramoto99 commented on aiaccel/__init__.py
> -
自動整形

2023-03-01 02:55 UTC, aramoto99 commented on aiaccel/abci/batch.py
> +    return f'{command} {" ".join(args)}'
~~~ bash
#!/bin/bash

#$-l rt_C.small=1
#$-j y
#$-cwd

source /etc/profile.d/modules.sh
module load gcc/11.2.0
module load python/3.8/3.8.13 
module load cuda/10.2
module load cudnn/8.0/8.0.5
module load nccl/2.8/2.8.4-1 
source ~/hoge/optenv/bin/activate

AIACCELPATH=$HOME/local/aiaccel-dev
export PYTHONPATH=$AIACCELPATH:$AIACCELPATH/lib

x1=1.0
x2=1.0
trial_id=0
config_file_path=/groups/3/gaa50073/aramoto-masahiro/examples/benchmark/config_w.yaml
output_file_path=/groups/3/gaa50073/aramoto-masahiro/examples/benchmark/work/result/0.hp
error_file_path=/groups/3/gaa50073/aramoto-masahiro/examples/benchmark/work/error/0.txt
start_time=`date "+%Y-%m-%d %H:%M:%S"`
result=`sh user.sh --x1 $x1 --x2 $x2 --trial_id 0 --config $config_file_path 2> $error_file_path`
exitcode=$?
result_array=($result)
y=${result_array[${#result_array[@]}-1]}
error=`cat $error_file_path`
end_time=`date "+%Y-%m-%d %H:%M:%S"`
if [ -n "$error" ]; then
    aiaccel-set-result --file $output_file_path --trial_id $trial_id --config $config_file_path --start_time $start_time --end_time $end_time --objective $y --error $error --exitcode $exitcode --x1 $x1 --x2 $x2 
else
    aiaccel-set-result --file $output_file_path --trial_id $trial_id --config $config_file_path --start_time $start_time --end_time $end_time --objective $y --exitcode $exitcode --x1 $x1 --x2 $x2 
fi
~~~

ジョブスクリプト生成例
結果ファイル生成用の処理を追加

2023-03-19 10:12 UTC, yoshipon requested changes
PRありがとうございます．ごめんなさい，遅くなりました．
ぱっと気になった点にコメントしました．

2023-03-19 10:12 UTC, yoshipon commented on aiaccel/__init__.py
> +                     search_algorithm_tpe)
relative importでなく，absolute importにしましょう．循環参照を防げます．

2023-03-19 10:12 UTC, yoshipon commented on aiaccel/abci/batch.py
> +class JobScrGenerator:
Scrが何か分からないので，略さず定義して下さい．Script?

2023-03-19 10:12 UTC, yoshipon commented on aiaccel/abci/batch.py
> +    code = JobScrGenerator()
Generatorのinstanceがcodeなのは変だと思います．

2023-03-19 10:12 UTC, yoshipon commented on aiaccel/abci/batch.py
> +class JobScrGenerator:
明日議論できればと思いますが，これクラスにするほどの機能でしょうか？
何かtemplate_job.sh みたいなのを作って，それを埋めるようなスクリプトで良いと思います．

2023-03-19 10:12 UTC, yoshipon commented on aiaccel/scheduler/abstract_scheduler.py
> +    #     """
以下コメントアウトではなく，削除でお願いします．すぐ復活させる予定があるのではないのですよね？

2023-03-31 03:05 UTC, aramoto99 commented
ブランチを更新しました（bd112d324a5712ec8d9411a70bdc4c5f779939fe）　

［差分］
- multi objective 対応 goalとユーザープログラムの出力をリストとして処理するよう変更
- 不要処理の削除
- JobScrGeneratorの廃止．（ジョブスクリプトのベースはコード内に埋め込み）
- relative importから，absolute importへ変更

2023-04-03 03:19 UTC, yoshipon approved these changes

2023-04-03 03:19 UTC, merged