fix random state initialization
aistairc/aiaccel pull request #258
Opened 2023-03-31 01:52 UTC by styamamoto

After this PR, `AbstractModule.__init__` initializes a member `_rng` as `numpy.random.RandomState` (not `None`).
Thus, the type of `_rng` is annotated by `RandomState` instead of currently-assigned `typing.Any`.
Also, a new method `write_random_seed_to_debug_log()` is added to write the used seed to the debug log.

2023-04-03 05:06 UTC, yoshipon requested changes

2023-04-03 06:04 UTC, styamamoto commented on aiaccel/scheduler/abstract_scheduler.py
> +        self.write_random_seed_to_debug_log()
logger が作られるのが継承先 (AbstractScheduler と AbstractOptimizer) なので，それぞれのコンストラクタに書くことになるかと思いますが，それでも問題ないでしょうか？

AbstractModule の pre_process に write_random_seed_to_debug_log() を移して，
継承先では super().pre_process() してから独自の処理を実装するように書き換えると，write_random_... は 1 回だけ書くだけでよさそうです．

2023-04-06 01:17 UTC, yoshipon commented on aiaccel/scheduler/abstract_scheduler.py
> +        self.write_random_seed_to_debug_log()
あーなるほどです．この辺，一本化したいですが，他の部分を先にいじらないと行けなさそうですね？
#221が閉じたら，一端approveします．

2023-04-06 04:34 UTC, styamamoto commented on aiaccel/scheduler/abstract_scheduler.py
> +        self.write_random_seed_to_debug_log()
logger の時と同様に，close しても良いのではないかと思いましたが．．．
コンフィグが整備されて，各モジュールのコンストラクタの実装が変わる際に，一度に直した方が分かりやすいような気もします．

2023-04-06 06:01 UTC, yoshipon approved these changes

2023-04-06 06:19 UTC, styamamoto commented on tests/unit/test_module.py
#221 で AbstractModule 用のテストが書き換わったようですが，
そこで使用されている create_numpy_random_generator() がこの PR で削除されるため，
該当箇所をテストスクリプトから削除しました．

2023-04-06 07:06 UTC, yoshipon approved these changes

2023-04-06 07:07 UTC, merged