fix codestyle test
aistairc/aiaccel pull request #26
Opened 2022-08-02 07:04 UTC by KanaiYuma-aist

Fix for `Pycodestyle Test` and `Flack8 Test`

- For `Pycodestyle Test`
   - Add white space
- For  `Flack8 Test`
   - Specify 'flake8' version as 4.0.1 (Update to flake8 occurred on 8/1 and the class 'ConfigFileFinder' became unusable)

2022-08-02 07:25 UTC, KanaiYuma-aist commented
@yoshipon @tkokada @aramoto99 

As a background to the creation of this pull requesut, an update of pycodestyle on 7/31 and Flack8 on 8/1 occurred, and the tests failed.

The pycodestyle modification was a minor modification to add spaces, and the test was successful, but the Flake8 modification was a moderate or larger modification, as the class `ConfigFileFinder` disappeared in the update, and I guessed that using the latest version would require a medium or larger modification.
Therefore, I modified it by once specifying the older version in the requirements.txt file.

Please let me know if you have any comments on this modification.

Translated with www.DeepL.com/Translator (free version)

---

このpull requesutを作成した経緯としまして、
7/31にpycodestyleの、8/1にFlack8のアップデートが発生し、
テストが失敗するようになりました。

pycodestyleの改修は、スペースを入れる軽微な修正でテストが成功したのですが、
Flake8の改修は、アップデートでクラス `ConfigFileFinder` が消えており、
最新バージョンを使うと、中規模以上の改修が必要と推測されるため、
一旦requirements.txtで古いバージョンを指定する形で改修しました。

こちらの改修について何かご意見あればお聞かせ下さい。

2022-08-03 01:51 UTC, aramoto99 approved these changes

2022-08-03 01:56 UTC, tkokada commented
Just my opinion, I didn't check any changes about ConfigFileFinder.

In general terms, the rollback to reffer old libraries, is not good.
But reducing the codes, is good.

2022-08-03 02:25 UTC, yoshipon commented
I agree with Okada san.

2022-08-03 02:28 UTC, yoshipon requested changes
I agree with Okada san.

What is the problem?
`aiaccel` seems not to depend on `ConfigFileFinder`, right?

2022-08-03 04:15 UTC, aramoto99 commented
This problem is occurring with `pytest-flake8`.
https://github.com/tholo/pytest-flake8/issues/87

This error occurs when flake8==5.0.1.
I think it is better to keep using 4.0.1 for the time being.

2022-08-03 04:23 UTC, tkokada commented
Thank you for sharing the link.

The bug about flake8_5.0.1 will be fixed in future but currently it's better to use 4.0.1, isn't it?

2022-08-03 04:28 UTC, yoshipon commented
I see, thank you!
is 5.0.0 not good?

2022-08-03 04:54 UTC, KanaiYuma-aist commented
Because an error occurs when using flake8 5.01, modified to continue to use 4.01, which has been working stably.

I also tried flake8 5.00 and got the same error.

(What is "Changes requested"?)

2022-08-03 04:59 UTC, yoshipon commented
I see. So, I think we don't have to change anything in this PR, but could you open an Issue to use the latest flake8 after the bug is fixed?
We will forget this issue in a few weeks...

2022-08-03 05:29 UTC, KanaiYuma-aist commented
In that case, until the flake8 error is fixed, the test will fail and other merge will not be possible, is this correct?

2022-08-03 05:37 UTC, yoshipon commented
No, this PR will be merged after you create the issue (as a reminder).

2022-08-03 05:48 UTC, KanaiYuma-aist commented
I see, I was mistaken.

I created the issues.
https://github.com/aistairc/aiaccel/issues/27

2022-08-03 05:48 UTC, yoshipon approved these changes

2022-08-03 05:48 UTC, yoshipon commented
Thank you!

2022-08-03 05:49 UTC, merged