Fix SobolOptimizer
aistairc/aiaccel pull request #281
Opened 2023-04-14 07:08 UTC by styamamoto

`SobolOptimizer` について，以下の３点を変更します．
- メンバ変数 `generate_index` を 0 で初期化 
    - もともと `None` で初期化していました．
- メンバ変数 `sampler` を `qmc.Sobol` で初期化
    - PR #258 で，`_rng` (`RandomState`) が `AbstractModule` のコンストラクタ内で初期化されるようになったため，`super().__init__()` を呼んだ後であれば，`qmc.Sobol` に `_rng` を渡せるようになりました．
    - resume が有効の場合， `sampler` は `pre_process()` で上書きされることになります．
- メソッド `generate_initial_parameter()` 内の警告文の条件を変更
    - もともと `super().generate_initla_parameter()` が `None` 以外を返した場合に警告を発するようなコードでしたが，`HyperPrameter.sample()` を使ってスーパークラスで初期値が自動生成されるため，常に警告が発せられていました．
    - `SobolOptimizer` では初期値が無効であるので，このことをユーザーに示すために，コンフィグに初期値が設定されていた場合にのみ警告を発するように変更しました．

2023-04-17 02:22 UTC, yoshipon requested changes
ありがとうございます．
概ね良いと思うのですが，「generate_index」って「何個生成したか」でしょうか？
そうであれば & 外部から参照されてないなら，「num_generated_params」とかの方が正しいように思います．
本PRに合わせて，変数名検討して貰えると幸いです．

よろしくお願いします．

2023-04-17 02:44 UTC, styamamoto commented
コメントありがとうございます．
>概ね良いと思うのですが，「generate_index」って「何個生成したか」でしょうか？
そうであれば & 外部から参照されてないなら，「num_generated_params」とかの方が正しいように思います．

「generate_index」は「何個生成したか」です．
名前を「num_generated_params」に変更いたしました．
外部からは参照されていないのですが，先頭にアンダースコアをつけて (_num_generated_params) プライベート変数であることを表した方が良いでしょうか？

修正していませんが，GridOptimizer でも同様の変数が「generate_index」になっているみたいです．

2023-04-17 03:13 UTC, yoshipon commented
ありがとうございます．全体のコーディング慣習を理解してないのですが，明確に_する文化があればお願いします．
> 修正していませんが，GridOptimizer でも同様の変数が「generate_index」になっているみたいです．
すみません，こちらもこのPRに混ぜておいて貰えると助かります．

2023-04-17 04:47 UTC, styamamoto commented
GridOptimizer のパラメータ名も変更いたしました．

\_ に関しては，付いているものと，そうでないものがあるようです．
ひとまずは現状を維持する方針で，\_ 無しにしています．

2023-04-19 01:02 UTC, styamamoto commented
pre_process での処理で，生成済みパラメータの数を取得する方法が，Sobol と Grid で異なるのですが，
どちらかに合わせた方が良いですか？

https://github.com/aistairc/aiaccel/blob/72a854bddaa6b7270c4d78a7adf9a0a382cd96eb/aiaccel/optimizer/sobol_optimizer.py#L44

https://github.com/aistairc/aiaccel/blob/72a854bddaa6b7270c4d78a7adf9a0a382cd96eb/aiaccel/optimizer/grid_optimizer.py#L132-L134

2023-04-19 01:22 UTC, styamamoto commented
BudgetSpecifiedGrid も生成済みパラメータ数を使いますが，もっと別の保持の仕方をしていました．
Optimizer が保持している GridPointGenerator がパラメータ数を記憶していて， pre_process では再取得していませんでした．
これも統一した方が良いかもしれません．
https://github.com/aistairc/aiaccel/blob/f657c37733402137e275290fd66ec7df8120179e/aiaccel/optimizer/_grid_point_generator.py#L424

2023-04-24 05:32 UTC, yoshipon approved these changes

2023-04-24 05:38 UTC, merged