Add dynamic loading of optimizer
aistairc/aiaccel pull request #34
Opened 2022-08-10 05:37 UTC by aramoto99

1. Changed the way optimizers are specified in the Config file.This change eliminates the need for reinstallation when the optimzier code is changed.
- `grid` -> `aiaccel.optimizer.grid`
- `random` -> `aiaccel.optimizer.random`
- `sobol` -> `aiaccel.optimizer.sobol`
- `nelder-mead` -> `aiaccel.optimizer.nelder_mead`
- `tpe` -> `aiaccel.optimizer.tpe`

2. When specifying an optimizer added independently by the user, specify it by path.
- (e.g.) '../optimizer/new'

3. constraints
- The name of the optimizer program file must be `search.py`.
- The name of the optimizer class must be `Optimizer`.
(e.g.) 　
https://github.com/aistairc/aiaccel/blob/01bf9542683eddd4dab22915201702d5ad878223/aiaccel/optimizer/grid/search.py#L65

2022-08-12 00:48 UTC, yoshipon commented
Thank you!
How about specifying the class name in the configuration to remain the original class name.
For example, `aiaccel.optimizer.grid.GridOptimizer`

2022-08-12 01:20 UTC, yoshipon requested changes

2022-08-12 01:20 UTC, yoshipon commented on aiaccel/optimizer/optimizer.py
> +    @singledispatchmethod
Is it really necessary to construct a generic function?

2022-08-21 11:43 UTC, yoshipon commented
Thank you for updating the PR.
It would be better to consider a simpler way to specify the standard optimizer (e.g., NelderMeadOptimizer).

2022-08-22 02:08 UTC, tkokada commented
@aramoto99 What kinds of rules are defined for any user optimizers? I think you find them using following codes.

https://github.com/aistairc/aiaccel/blob/6b3963ddd003c0a4e0f0a3fdc7217f64a92f5d89/aiaccel/start.py#L512-L519

2022-08-22 08:30 UTC, yoshipon approved these changes
Thank you, LGTM!

2022-08-22 09:12 UTC, merged