Add nelder-mead sampler
aistairc/aiaccel pull request #346
Opened 2024-01-09 07:53 UTC by KanaiYuma-aist

Nelder-Mead Sampler と、対応したテストを追加しました。

2024-01-15 01:54 UTC, yoshipon requested changes
PRありがとうございます．
全体的にAnyが多いのが気になりますが，Simplex等の入力はfloat32, 64等の数値型だと思うので，極力Anyを減らして貰ってもよいでしょうか？
特に ` | Any` となっている部分は，型を付けていないのと同じになってしまうので，やむを得ない場合を除き，割けるべきだと思います．

`mypy` のチェックが厳しすぎる系の話であれば，そちらの設定を修正した方が良いと思うので，ミーティング等でご指摘下さい．

2024-01-15 01:54 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        self.yr: float | Any = None  # value of reflect vertex
これってSimplexと分ける必要ありますか？ マージできる気がします．

2024-01-15 01:54 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        self.state: NelderMeadState = NelderMeadState.Initial
Stateはsimplexに持たせた方が分かりやすいような気がしますが，samplerの方が良いでしょうか．

2024-01-15 01:54 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +coef: dict[str, float] = {"r": 1.0, "ic": -0.5, "oc": 0.5, "e": 2.0, "s": 0.5}
APIから修正できないので，Simplexのコンストラクタ引数 & 更にはSamplerのコンストラクタ引数にしてください．
コンテナとしてdict でなく，dataclasses.dataclass 使って欲しいです．

2024-01-15 05:42 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        self.state: NelderMeadState = NelderMeadState.Initial
NelderMeadSampler内に存在するoptuna.samplersに関連しない関数を別クラス(NelderMeadAlgorism等)に分離する形で改修します

2024-01-16 05:45 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +coef: dict[str, float] = {"r": 1.0, "ic": -0.5, "oc": 0.5, "e": 2.0, "s": 0.5}
coefを各コンストラクタ引数に追加、dataclasses.dataclass で定義しました。
f7f34c9e7572e85ee2555650c4ca53d0fefe36ff

2024-01-16 05:46 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        self.state: NelderMeadState = NelderMeadState.Initial
NelderMeadAlgorism クラスを追加し、State含んだ optuna.samplersに関連しない処理を移動させました。
dcfca020d958c196ad101565d11aa25e0a7d15a1

2024-01-16 05:49 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        self.yr: float | Any = None  # value of reflect vertex
NelderMeadAlgorism クラスに統合しました。
dcfca020d958c196ad101565d11aa25e0a7d15a1

2024-01-23 02:36 UTC, KanaiYuma-aist commented
NelderMeadAlgorismの実装を yield を用いて、極力オリジナルの NelderMead に近い形で改修しました。
UnitTest は並列化実装の調査・改修後に修正します。

2024-01-23 03:43 UTC, yoshipon requested changes
修正ありがとうございます．
数理的なアルゴリズムの実装において，1回しか使われない・使う予定のないメソッドは作成する必要がないように思います．
また，分割の結果 `self.storage` が必要になっているようなので，纏めてしまった方が良いと思います．

コード本体にコメントしたので，ご確認お願いします．

2024-01-23 03:43 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            self.centroid()
副作用のみの関数だと，何をしているのかぱっと分からないので，
```suggestion
            yc = self.centroid(self.xxx)
```
のように，入出力で作用が分かるように書いて頂いても良いでしょうか．

2024-01-23 03:43 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            yield from self.reflect()
ここで yield from されているのは，恐らく `self.func` がyieldするかもしれないし，しないかもしれないからと思うのですが，これはロジックが不透明になるので避けた方が良いと思います．
NMアルゴリズムとしては範囲内外を判断せず，Samplerの方で範囲外になっていれば即infを返す実装にした方が読みやすいと思いますがいかがでしょう？

```suggestion
            yield (r := yc + self.coef.r * (yc - self.vertices[-1]))
```
とすれば，メソッド作る必要もなくぱっと読めて良いかと．

2024-01-23 03:43 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +
if文前後の改行は削除して下さい．

2024-01-23 03:43 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            fr = self.vertex_queue.get().value
`get().value` されていますが，このqueには クラスでなくfloat詰めれば良いと思うのですが如何でしょうか．

2024-01-23 03:43 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                self.vertices[-1] = self.storage.r
多分，`storage` クラスは不要になったと思います．
上の修正と合わせて，こんな感じで書けば良いと思います．
```suggestion
                self.vertices[-1] = r
```

2024-01-23 03:43 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                    yield from self.shrink()
shrinkが2回でてくるこの部分は，メソッドに分けず下記のように直せると良い気がしました．
```suggestion
            elif self.values[-2] <= fr < self.values[-1]:
                yield (oc := ...)
                foc = self.vertex_queue.get()

                if foc <= fr:
                    self.vertices[-1], self.values[-1] = oc, foc
                else:
                    shrink_requied = True
            elif self.values[-1] <= fr:
                yield (ic := ...)
                fic = self.vertex_queue.get()

                if fic < self.values[-1]:
                    self.vertices[-1], self.values[-1] = ic, fic
                else:
                    shrink_requied = True

            if is_shrink:
                pass  # shrinkの操作を書く
                shrink_requied = False
```

2024-01-23 03:43 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        self.NumofInitialCreateTrial: int = 0
変数名はsnake_caseにして下さい．

2024-01-23 03:43 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            temp.append(self.vertex_queue.get())
```suggestion
        vertexes? = [self.vertex_queue.get() for _ in range(self.dimension + 1)]
```

2024-01-23 04:38 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            fr = self.vertex_queue.get().value
vertexクラスを用いている意図としては、initialやshrinkを並列化のために座標(coordinate)と計算結果(value)を紐付けておきたいというものがあります。
initial, shrink 以外の操作では座標を紐付けなくても、直列実行しか行わないので計算結果のみを利用しています。

2024-01-23 05:09 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            fr = self.vertex_queue.get().value
コメントありがとうございます．
であれば，他の部分もちゃんとvetexとvalueが意図したものかチェックすべきだと思います．
ただし，その場合はコードが煩雑になると思うので，yieldした順番に put される前提で書いてしまった方が良いと思います．

2024-01-23 05:19 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +    def search(self) -> Generator[np.ndarray[float, float], None, None]:
↑の書き方をするには， `__iter__` にすると良さそうです．
```suggestion
    def __iter__(self) -> Generator[np.ndarray[float, float], None, None]:
```

2024-01-23 05:26 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        while True:
ひとまず、num_iterationsをNelderMeadSamplerの引数から指定できる形で改修しました。
（ここで言うnum_iterations と 試行回数 trial_id は厳密には違う　みたいな議論を過去行ったことを思い出しました）

5c7077e4d95ae9e99b1b43db4d69ba29def5d797
24e848e1a02641c38245a0f6b1a715e3d89ca12e

2024-01-23 05:27 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            self.centroid()
> 数理的なアルゴリズムの実装において，1回しか使われない・使う予定のないメソッドは作成する必要がないように思います．
こちらの改修の都合で self.centroid 関数も削除されました。

2024-01-23 05:30 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            yield from self.reflect()
対応しました。
(yieldの書き方の勉強になりました。ありがとうございます。)

71f29148f4b52151a458aecc2196d89b52d2d224

2024-01-23 05:31 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +
対応しました。

fb3ac443202ced8e4eefbb19653504bdbf21f261

2024-01-23 05:31 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                self.vertices[-1] = self.storage.r
対応しました。

c0f682669b698771a12bc7ead47a5a0922c39061

2024-01-23 05:32 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                    yield from self.shrink()
対応しました。

71f29148f4b52151a458aecc2196d89b52d2d224

2024-01-23 05:33 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        self.NumofInitialCreateTrial: int = 0
対応しました。

c0f682669b698771a12bc7ead47a5a0922c39061

2024-01-23 05:34 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            temp.append(self.vertex_queue.get())
対応しました。

71f29148f4b52151a458aecc2196d89b52d2d224

2024-01-23 05:59 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                    yield from self.shrink()
こちら，
* yield (...) ficのあとの改行
* ic, ficの代入を1行に
* shrink_required = Falseは最後のif文のとこだけ
が反映頂けていないようなので修正お願いします．


他のverticesへの代入も三項演算子で1行にすると良いと思います (ruffで提案されると思います)．
また，Samplerの方にもcamel caseが残っているので，修正お願いします．

2024-01-23 06:04 UTC, yoshipon requested changes

2024-01-23 06:04 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            fr = self.vertex_queue.get().value
合わせて， yield は頂点だけ返して0は不要かと思ったんですが，こちら必要でしょうか？

2024-01-23 06:04 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            self.order_by()
メソッド名から内容が不明瞭なので，修正お願いします． `sort_vertices` とか…？

2024-01-23 06:04 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        yield from self.initial()
initial / shrinkはsearchの中に入れてしまって良いかと．
initialはoptunaと分離できますか？

2024-01-23 06:04 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            self.yc = self.vertices[:-1].mean(axis=0)
メンバにする必要はないかと思います．
```suggestion
            yc = self.vertices[:-1].mean(axis=0)
```

2024-01-23 06:50 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            fr = self.vertex_queue.get().value
ひとまず queue は valueのみを保持するようにして、
並列時は並列ジョブがすべて実行完了するまでsamplerが value を保持して、実行完了後にoptuna の trial_id 順に（yieldした順番に）queueにputするように改修しました。

644282a15fcaaf49fa6f82137a33115d924e2287

> yield は頂点だけ返して0は不要かと思ったんですが，こちら必要でしょうか？

そちらは並列実行が可能な数を返しています。
暫定的な並列実行テスト時に利用しているだけなので、後々削除予定です。

2024-01-23 07:13 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                    yield from self.shrink()
反映しました。

93d182a24057f232756fd3e9b88416e4e03b26cc

>  (ruffで提案されると思います)

改修前に ruff を実行してみても、特に何も出てきませんでした。

```
$ ruff check --line-length 120 --fix aiaccel/hpo/samplers/nelder_mead_sampler.py
$ 
```

2024-01-23 07:14 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +    def search(self) -> Generator[np.ndarray[float, float], None, None]:
反映しました。

c2f5c94acb0956af7e84f7140b153e7c0c7427ec

2024-01-23 07:22 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            self.order_by()
> 1回しか使われない・使う予定のないメソッドは作成する必要がないように思います．

self.order_by() もこちらに該当するメソッドだったので、削除しました。

7ee1e861c579f8a2f6c3f9c110ed60e1c1cb0e6e

2024-01-23 07:23 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            fr = self.vertex_queue.get().value
状況のご説明ありがとうございます．並列方法が確定していないので，一旦削除してしまいましょう．

2024-01-23 07:23 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                    yield from self.shrink()
ありがとうございます．1行の時だっただけかも…
この前確か提案された覚えがあるんですよね．

2024-01-23 07:24 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            self.order_by()
修正ありがとうございます．
こちらコメントの `order by` だけだと，by 何か分からないので，
```
# sort vertices by their values
```
とかに直して頂いても良いでしょうか．

2024-01-23 07:27 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                    yield from self.shrink()
```
shrink_required = False
```
がまだ残っていますので，反映をお願いします．

2024-01-23 07:27 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        yield from self.initial()
こちら反映したところ、ruff でエラーが発生しました。
メソッド内の分岐が多くなりすぎたことが原因と思われます。

7ee1e861c579f8a2f6c3f9c110ed60e1c1cb0e6e

> initialはoptunaと分離できますか？

自前でランダムサーチを書くだけなので、可能です。
対応します。

2024-01-23 07:31 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                    yield from self.shrink()
あと，三項演算子の修正もお願いします…

2024-01-23 07:34 UTC, yoshipon requested changes

2024-01-23 07:34 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                    self.vertices[-1], self.values[-1] = yr, fr
三項演算子，使えるのはここだけでしたね．すみません．
```suggestion

                self.vertices[-1], self.values[-1] = ye, fe if fe < fr else yr, fr
```

2024-01-23 07:34 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                    self.vertices[-1], self.values[-1] = yr, fr
commit suggestion押せば反映されると思いますので，活用下さい．

2024-01-23 07:34 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        yield from self.initial()
暫定処置として initial / shrink を再分離しました。

2927a85523dc0b2632a1df34a46b8bbe7b0f7b13

2024-01-23 07:38 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        yield from self.initial()
> こちら反映したところ、ruff でエラーが発生しました。
初期化時の1つ目のfor文は消せると思います．
```
np.random.uniform(lows, highs, ([初期点の個数], n_dim))
```
とすると良いと思います．

2024-01-23 07:39 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            self.yc = self.vertices[:-1].mean(axis=0)
反映しました。

2aa3d7ff62072b93d9286f8606620e7ebc62aa3f

2024-01-23 07:45 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            fr = self.vertex_queue.get().value
反映しました。

a63da2587f46107899970b1362fd00259ddd4632

2024-01-23 07:47 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                    yield from self.shrink()
反映しました。

0dcfbe532a6b1ac96749f96cd3fb4a82c103e07d

2024-01-23 07:48 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            self.order_by()
反映しました。

aa4acbbf09a3d7a4bfd705a9a58f326179008fbe

2024-01-23 08:08 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                    yield from self.shrink()
上記コミットの Optimizer Algorithm Test でエラーが発生しました。
`UnboundLocalError: local variable 'shrink_requied' referenced before assignment`

1度も shrink_requied を定義せずにif文の判定を行っていることが原因のようだったので、__iter__の最初に shrink_requied = False を追加しました。

2024-01-23 08:47 UTC, KanaiYuma-aist commented
@yoshipon 
pushありがとうございます。

Validate code formats や Optimizer Algorithm Test がエラーになる軽微な typo を修正しました。
また、 generate_initial_vertices は __iter__ 内部に移しても問題無かったので、削除しました。

2024-01-23 13:47 UTC, yoshipon commented
修正ありがとうございました．細かい部分何か所か修正させて頂きました．
`ruff format` が抜けていたので，mypy / ruff等はpre-commitで確認頂くと良い気がします．

seedですが，np.random.seedを指定するのでなく，rngのインスタンスを保持しておいて，そのseedを設定するように修正頂いて良いでしょうか．
あと，やっと理解できたのですが，確かにnum_iterationsって反復回数ではないから意味がないんですね．削除しました．
あと，verticesとvaluesについて，可視化しようと思うとメンバで持ってないと困りますね… ごめんなさい，これも戻しました．

2024-01-24 00:53 UTC, KanaiYuma-aist commented
np.random.RandomState に seed を設定し、それを用いて乱数生成するように変更しました。

9a2f5daf9435f3e7c083cf5c65a824b79f48980f

2024-01-24 03:07 UTC, yoshipon commented
修正ありがとうございます．では一旦，Optunaでの並列サンプリングについて調査頂き，Slack等でご報告頂いて議論できればと思います．

2024-01-25 08:40 UTC, KanaiYuma-aist commented
optunaの機能に study.enqueue_trial があります。
https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.enqueue_trial

これは初期パラメータを固定したりするのに使われる機能ですが、現状のNelderMeadSamplerでこの機能を用いようとすると想定していない挙動を取ります。

study.enqueue_trial で指定されたパラメータを NelderMeadAlgorism に反映する機能が無いため、
パラメータを study.enqueue_trial で固定しようとすると、
NelderMeadAlgorism 内ではパラメータはランダムで選ばれたパラメータが利用され、
計算結果のみ study.enqueue_trial で指定されたパラメータの結果が利用されます。

例
ユーザプログラムを f(x, y) とした時、
study.enqueue_trial({"x": 5, "y": 5}) が実行されると、
パラメータ {"x": 5, "y": 5} の計算結果 f(5, 5) となるべきところが、
パラメータ {'x': 3.745401188473625, 'y': 9.50714306409916}(ランダムに選ばれたパラメータ) の計算結果 f(5, 5) となる。

2024-01-29 08:46 UTC, KanaiYuma-aist commented
ひとまず並列化処理を削除し、並列実行時（パラメータ出力不可のタイミングで before_trial が呼ばれた時）と
enqueue_trial 実行後に ask が実行された時（trial.system_attrs["fixed_params"] が存在する時）に RuntimeError を発生させるように改修しました。

1e7e6e3b308a684830e92d186b4f10e724875808

2024-02-05 04:30 UTC, yoshipon requested changes
修正ありがとうございます．Samplerの各メソッドについてですが，できれば意味ごとに改行を挟んで頂けると幸いです．
他の修正をお願いしたい部分は下記の通りコメントしましたので，ご確認お願いします．

2024-02-05 04:30 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        self.is_ready: bool = False
右辺の型から型推論できると思うので，型アノテーションは不要な気がしましたが如何でしょう？
```suggestion
        self._rng = np.random.RandomState(seed)
        self.is_ready = False
```

2024-02-05 04:30 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        yield self.vertices[-1]
後ろにもこの形が出てきて結構複雑になってしまいますね…
```suggestion
        yield from self.yield_vertices(self.vertices)
```
みたいなものを作って，全てのyield, yield fromをここに詰める，引数に含まれる要素数に合わせてself.is_readyを適宜制御する実装はいかがでしょうか？

2024-02-05 04:30 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                self.values[1:] = [self.value_queue.get() for _ in range(len(self.vertices) - 1)]
ごめんなさい，今気づいたんですが，is_readyってget()待ちの前後に付けるものかと思ったんですがいかがでしょう．
yieldしてる間は is_ready あっても無くても変わらないような…

2024-02-05 04:30 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            self._search_space[param_name] = list(param_distribution)
```suggestion
        self._search_space = {name: list(dist) for name, dist in search_space.items()}
```
と書くとすっきりできそうです．Python3.7からdictはordered dictなので，sortは不要かと思いました．

2024-02-05 04:30 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            raise RuntimeError("Cannot output parameters.")
初期状態でis_readyがfalseなので，`num_running_trial > 0` は不要かと思ったんですがいかがでしょう？

2024-02-05 04:30 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            raise RuntimeError("Cannot output parameters.")
↓のErrorと合わせて，NMは現在パラレル動作をサポートしませんみたいなメッセージを吐けると良いかと思いました．前後のコメントアウトは無くて良いと思います．

2024-02-05 04:30 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        if "fixed_params" in trial.system_attrs:
`system_attrs` は3.1.0からDeprecatedらしいので，回避方法を確認頂けると幸いです．
https://optuna.readthedocs.io/en/stable/reference/generated/optuna.trial.Trial.html#optuna.trial.Trial.system_attrs

2024-02-05 04:30 UTC, yoshipon commented on pyproject.toml
> +    "optuna>=3.4.0,<4.0.0",
まだ4.0.0はリリースされていないので，>=3.4.0で良いと思います．

2024-02-05 04:49 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            raise RuntimeError("Cannot output parameters.")
self.num_running_trial > 0 を消すと、is_ready = False の時（＝reflect 等の並列化不可能な操作を行っている時）に一律で例外がスローされてしまいそうです。

2024-02-05 05:59 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            raise RuntimeError("Cannot output parameters.")
self.num_running_trial > 0 に相当するフラグ管理を NelderMeadAlgorism 内で行うように改修する方針で考えてみます。

2024-02-05 06:00 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                self.values[1:] = [self.value_queue.get() for _ in range(len(self.vertices) - 1)]
（開発者会議メモ）
一旦 is_ready の挙動は現行のままで進めます。

2024-02-06 02:04 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            raise RuntimeError("Cannot output parameters.")
num_running_trial を NelderMeadAlgorism 内に移し、after_trial 毎に NelderMeadAlgorism.finish_trial を呼び出して、そちらでフラグ変数 is_all_trials_finished を管理するように改修しました。

d4097e23c9ada3b49115a19b3cbeba2fc9d854c8

2024-02-06 02:05 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        yield self.vertices[-1]
NelderMeadAlgorism.yield_vertices を追加しました。

d4097e23c9ada3b49115a19b3cbeba2fc9d854c8

2024-02-06 07:36 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        if "fixed_params" in trial.system_attrs:
現行optuna における enqueue_trial を判別する方法は、system_attrs["fixed_params"]の有無で判別する以外に無いように思えます。
https://github.com/optuna/optuna/blob/53d85542ae8e291101e929ceb4bbbdb146609613/optuna/study/study.py#L807

v5.0.0 で削除されるようなので、 v5.0.0 以降の代替機能も調べたのですが、見当たりませんでした。

2024-02-07 07:17 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            raise RuntimeError("Cannot output parameters.")
> ↓のErrorと合わせて，NMは現在パラレル動作をサポートしませんみたいなメッセージを吐けると良いかと思いました．前後のコメントアウトは無くて良いと思います．

該当箇所のエラーはパラレル実行をしようとした時以外にも、不適切なタイミングで ask を実行した際にも発生しうるので、「現在パラレル動作をサポートしません」のようなメッセージは語弊がありそうです。
また、 ask-tell を用いたパラレル実行であれば(IsReadyを参照する必要はありますが)、サポートしていないわけではないので、その意味でも語弊がありそうです。

2024-02-07 07:29 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        self.is_ready: bool = False
反映しました。

01347c49aa643c387d322b40ce8f75dc337857e1

2024-02-07 07:30 UTC, KanaiYuma-aist commented on pyproject.toml
> +    "optuna>=3.4.0,<4.0.0",
反映しました。

f8b140e0e803f5ddc0720fba7e758b403ea90549

2024-02-09 06:48 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        if "fixed_params" in trial.system_attrs:
Trial クラスに Trial._is_fixed_param メソッドがあり、それで fixed_param の存在判定を行っているようでしたが、
Sampler からは _is_fixed_param は参照不可能のようです。

2024-02-12 15:03 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            raise RuntimeError("Cannot output parameters.")
なるほどです．ありがとうございます．

2024-02-12 15:03 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        if "fixed_params" in trial.system_attrs:
了解です．ありがとうございます．

2024-02-12 15:21 UTC, yoshipon requested changes
修正ありがとうございます！ やっぱりyieldだと煩雑になってしまいますね…
アルゴリズムを別スレッドで起動して，入出力ともにqueueにして頂いてもよいでしょうか？
queueであれば，空であることはgetすれば分かると思いますので，実装が単純化に出来るかなと思います．

2024-02-12 15:21 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        seed: int | None = None,
この部分ですが，seedでなくrng与える仕様に変更お願いします．
全体で1つのgenerator使いたい場合にその方が汎用性高くなるので．

2024-02-12 15:21 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +    def yield_vertices(self, vertices: np.ndarray[Any, Any]) -> Generator[np.ndarray[Any, Any], None, None]:
2Dのndarrayでなくlist[ndarray]でお願いします．その方が__iter__内を短く出来ると思います．

2024-02-12 15:21 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +    def yield_vertices(self, vertices: np.ndarray[Any, Any]) -> Generator[np.ndarray[Any, Any], None, None]:
型はできるだけAnyを避けて指定して頂けると幸いです．

2024-02-12 15:21 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            raise RuntimeError("Cannot output parameters.")
ありがとうございます．
> 不適切なタイミングで ask を実行した際

というのは具体的にはどういう状況でしょうか？
エラーメッセージを読んで「なぜoutputできないのか」が類推できる方がユーザによって親切と思います．
「パラレルで実行したり，XXX (↑の状況) で実行したりしていませんか？」などをメッセージに付け加えた方が良い気がしています．

2024-02-13 01:54 UTC, KanaiYuma-aist commented
> 不適切なタイミングで ask を実行した際
> 
> というのは具体的にはどういう状況でしょうか？

ask-tell で reflect 後等のパラメータが出力できないタイミングで ask し、tell を未実行の状態で ask をもう一度呼び出すような状況を想定しています。

> エラーメッセージを読んで「なぜoutputできないのか」が類推できる方がユーザによって親切と思います．
> 「パラレルで実行したり，XXX (↑の状況) で実行したりしていませんか？」などをメッセージに付け加えた方が良い気がしています．
> 

承知しました。そのように付け加えます。

2024-02-13 05:19 UTC, yoshipon commented
ご説明ありがとうございます．
> tell を未実行の状態で ask をもう一度呼び出すような状況を想定しています。

これは状況的には「askのparallel callはできない」と等価だと思うのですがいかがでしょうか．実際複数のtrialが並列して存在しているので．

2024-02-13 05:34 UTC, KanaiYuma-aist commented
そうですね。「askの並列呼び出し(parallel call)はできない」のメッセージを表示するほうが具体的で良さそうです。
そちらに変更しておきます。

2024-02-14 05:23 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +    def yield_vertices(self, vertices: np.ndarray[Any, Any]) -> Generator[np.ndarray[Any, Any], None, None]:
対応しました。

b378924508bb2f796bbfddc9c2f1ea7252688e93

2024-02-14 05:23 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        seed: int | None = None,
対応しました。

efa3789ee989ff2133db73d08397fe08bfaa0356

2024-02-15 07:59 UTC, KanaiYuma-aist commented
vertex_queue を追加し、パラメータの受け渡しを queue で行うように改修しました。

is_ready の制御は NelderMeadAlgorism が行うのが適切だと思い、get_vertex, put_vertices メソッドを追加して、それらで is_ready を制御するようにしました。

924cdd7bb3d2e2efe34aa3b857c43b88d7e18706

2024-02-16 07:43 UTC, KanaiYuma-aist commented
is_ready を NelderMeadAlgorism 内に保持させると、非同期処理の都合で記述が複雑になるので、NelderMeadSampler 内に移動させました。
（vertex_queue が空かどうかで is_ready を制御しようとすると、 reflect の計算処理中に ask が実行されると、本来 reflect のパラメータを返せるタイミングにも関わらず、vertex_queue にパラメータが put される前故に False 扱いになってしまう等）

71e80820f9aa71b85fc3ba7432e6aa5841ea88cd

2024-02-19 04:24 UTC, KanaiYuma-aist commented
(開発者会議メモ)
・ミューテックス(threading.lock？)を利用して、 is_ready を削除する（vertex_queue が空の時に ask が実行されたらエラーを raise するようにする）
・threading を立ち上げるのは NelderMeadAlgorism 内にする
・NelderMeadAlgorism 内にqueue 用の setter getter を作成する

2024-02-27 08:27 UTC, KanaiYuma-aist commented
NelderMeadAlgorism を yield を用いる形に改修しました。

なお、_waiting_for に関しては、yield と return を両立する形だと mypy でエラーが出たので、
返り値の result をメンバにして yield のみを用いる形に変更しました。

https://github.com/aistairc/aiaccel/blob/7d3f9a971803a365b4766afdc41a5ffb853e8e2a/aiaccel/hpo/samplers/nelder_mead_sampler.py#L59-L65

2024-02-28 06:30 UTC, yoshipon commented
ありがとうございます。
Generatorの型をNone, None, Noneでなく、正しく指定すればmypy通りませんでしょうか？

2024-02-28 07:52 UTC, KanaiYuma-aist commented
型の書き方を勘違いしていただけでした。（引数の3つ目に return value の型を書くんですね・・・）

修正してメンバの results は削除しました。

2024-03-01 15:02 UTC, yoshipon requested changes
修正ありがとうございます。
詳しくは月曜日議論できればと思いますが、ユニットテストで、reflect, expand等の個別のパスを確認する必要はない気がしています。
代わりに、results.csvに書かれている処理が、必ず全てのパスを通るような結果に調整頂いて、coverageを見る方が良いかと感じています。
(テストコードが短くなるので)

あと、これも良く分かってないので月曜日教えて頂けると幸いなのですが、
結合テストの例で通ってないパスをユニットテストで検証するような書き方でも良いのではと少し感じています。

2024-03-04 00:39 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +    def _waiting_for(self, num_waiting: int) -> Generator[None, None, list[float]]:
_waiting_for 内部で yield されるのは que が空だった時の None のみですが、それでも np.ndarray を指定すべきですか？

2024-03-04 00:51 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        self.values = np.array(results)
この書き方を行うと、 invalid syntax が発生します。
（yield を括弧内に書いている部分？）

```
aiaccel_env/lib/python3.8/site-packages/_pytest/python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)                                       
aiaccel_env/lib/python3.8/site-packages/_pytest/pathlib.py:567: in import_path                                     
    importlib.import_module(module_name)                                                                           
../../../anaconda3/lib/python3.8/importlib/__init__.py:127: in import_module                                       
    return _bootstrap._gcd_import(name[level:], package, level)                                                    
<frozen importlib._bootstrap>:1014: in _gcd_import                                                                 
    ???                                                                                                            
<frozen importlib._bootstrap>:991: in _find_and_load                                                               
    ???                                                                                                            
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked                                                      
    ???                                                                                                            
<frozen importlib._bootstrap>:671: in _load_unlocked                                                               
    ???                                                                                                            
aiaccel_env/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:186: in exec_module                           
    exec(co, module.__dict__)                                                                                      
tests/sampler/nelder_mead/test_nelder_mead.py:7: in <module>                                                       
    from aiaccel.hpo.samplers.nelder_mead_sampler import NelderMeadSampler                                         
E     File "/home/member/hpopt/aiaccelv2/aiaccel/aiaccel_env/lib/python3.8/site-packages/aiaccel/hpo/samplers/nelder_mead_sampler.py", line 72                                                                                        
E       self.values = np.asarray(yield from self._waiting_for(len(self.vertices)))                                 
E                                ^                                                                                 
E   SyntaxError: invalid syntax      
```

2024-03-04 01:39 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        return results
コードとしては通りますが、_waiting_for の返り値の型アノテーションが float | list[float] になり、
下記のような _waiting_for の返り値を比較する箇所で float であることを判定するif文を入れないとmypyでエラーが出ます。

https://github.com/aistairc/aiaccel/blob/c68ff7682cf38a6cf8df68e0a2e9efe9c844b7ce/aiaccel/hpo/samplers/nelder_mead_sampler.py#L96-L100

2024-03-04 01:52 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        if self.is_within_range(cooridinate):
反映しました。

a682782ffd75bf975612f4bf2fd89af5f63814f9

2024-03-04 01:53 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        self._search_space = {name: list(dist) for name, dist in search_space.items()}  # Memorise parameter order.
動作に問題なかったので、修正しました。

475232ecac7ab13637e448a6672255bea0111c27

2024-03-04 01:54 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            return self._get_cooridinate()
whileループを使う形に修正しました。

e363f945927035ba3402c421e9265416b6a3ea01

2024-03-04 01:56 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        self._num_waiting -= 1
削除しました。

2024-03-04 06:40 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +    def _waiting_for(self, num_waiting: int) -> Generator[None, None, list[float]]:
開発者会議メモ
空行だけ削除して、他はそのままにする

2024-03-04 06:40 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        return results
開発者会議メモ
_waiting_for の他に _waiting_for_one のような1つの結果のみを待つ関数を作成する

2024-03-04 06:44 UTC, KanaiYuma-aist commented
開発者会議メモ
・ユニットテストの expand 等のテスト内部を一般化する
・Sampler内部の Coordinate の名称が optuna 的に適切かどうかを調査する
・user_attrs の中身の先頭文字は小文字か大文字化 optuna 的にどちらが正しいのかを調査する

2024-03-06 06:42 UTC, KanaiYuma-aist commented
・Sampler内部の Coordinate の名称が optuna 的に適切かどうかを調査する

TPESampler を参考にすると、適切なのは param sample 辺り？
https://github.com/optuna/optuna/blob/master/optuna/samplers/_tpe/sampler.py

・user_attrs の中身の先頭文字は小文字か大文字化 optuna 的にどちらが正しいのかを調査する

GridSampler を参考にすると、小文字が正しい。
https://github.com/optuna/optuna/blob/master/optuna/samplers/_grid.py

2024-03-06 10:27 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +        self.values = np.array(results)
こう書いても良いかもしれませんね。
```suggestion
        self.vertices = self._rng.uniform(lows, highs, (self.dimension + 1, self.dimension))
        self.values = np.empty(self.dimension + 1)

        yield from self.vertices
        self.values[:] = yield from self._waiting_for_list(len(self.vertices))
```

2024-03-13 01:10 UTC, KanaiYuma-aist commented
下記のペンディングになっている項目について調査・ローカルにて仮実装しました。

- enqueue_trial について

現状のコードに対して、ローカルにて initial 時限定で enqueue_trial が反映できるように仮実装しました。
（まだpushはしていません。）
問題なければこのまま実装してしまいたいのですが、
nelder_mead のメインループ中に enqueue_trial が発生した時の挙動はどのようにするのが適切でしょうか？
（以前 enqueue_trial についてお話した際は、ループの最初 reflect に戻る？ような処理を行うと聞いた覚えがあります。）

- 並列化について

現状のコードであれば、 NelderMeadAlgorism の引数 block （queue.get 時にブロックするかどうか）を True にすれば、
study.optimize(njobs=3)で並列化できることを確認しました。
ただし、block = True の状態だと、ユーザが ask-tell で sampler を用いると、実装によっては queue.get 時にデッドロックする可能性が有ります。
上記を踏まえて、並列実行の ON / OFF ができるような引数を追加するのが適切かと思うのですが、いかがでしょうか？

2024-03-18 05:55 UTC, KanaiYuma-aist commented
開発者会議メモ
- enqueue_trial について
  - 通常の NelderMead で決定されるパラメータの他に、enqueue されたパラメータも並列で計算できるようにする。
  - NelderMead で決定されたパラメータと、enqueue されたパラメータとで比較して、enqueueされたパラメータの方が良ければ、reflectに戻ってenqueue されたパラメータを単体に取り込む。
  - enqueue されたパラメータの方が悪ければ、NelderMead で決定されたパラメータを取り込んで、通常通り NelderMeadの処理を続行する。
- 並列化について
  - 上記の enqueue_trial の並列化をできるようにする。
  - threading.lock の処理は NelderMeadAlgorism 内に記述して、 NelderMeadAlgorism をスレッドセーフとする。
  - 他は基本的には上記のコメントの「並列化について」の通りにする。

2024-03-19 01:07 UTC, KanaiYuma-aist commented
> NelderMead で決定されたパラメータと、enqueue されたパラメータとで比較して、enqueueされたパラメータの方が良ければ、reflectに戻ってenqueue されたパラメータを単体に取り込む。

enqueue されたパラメータの方が良かった場合、
そのパラメータを単体の一番valueが低い vertexと置き換えて reflect を行う 
（単体の value(s) >  enqueue されたパラメータのvalue > NelderMead で決定されたパラメータのvalue の場合は、そのまま NelderMeadの処理を続行する？）
or
そのパラメータを reflect で計算されたパラメータとして扱い、その後の処理(expand or inside_contract or outside_contract)を行う
のどちらの方が良いでしょうか？

（後者は NelderMead の計算が崩れそうなので、一旦前者で進めます。）

2024-03-19 06:24 UTC, KanaiYuma-aist commented
懸念点として、（今までもランダムで打つ初期点で発生する確率は一応存在しましたが、）
enqueue されたパラメータを反映した結果、アフィン独立ではない単体が生成された時にどうするかというものが挙げられますね。

2024-03-22 07:32 UTC, KanaiYuma-aist commented
3/18の開発者会議内で協議した内容に従って、 enqueue_trial と並列化に対応しました。

以下、差分について補足します。

- NelderMeadAlgorism
  - enqueue_trial にて追加されたパラメータと計算結果を受け取る queue を追加しました。(enqueue_vertex_queue, enqueue_value_queue)
  - put_enqueue_vertex メソッドでは、enqueue_trial で指定が無かったパラメータについては、ランダムでパラメータを決定してから enqueue_vertex_queue に put します。
  - _waiting_for_list メソッドで、 enqueue_value_queue から計算結果を取り出す処理を追加しています。
  - _initialization メソッドでは、engueue_trial で追加されたパラメータ数が dimension + 1 以下の場合に、ランダムでパラメータを生成して、yield で返します。
    - パラメータ数が dimension + 1 よりも多い場合は、より良い dimension + 1 個のパラメータを選択して、初期 Simplex とします。
  - _recontract_simplex メソッドでは、engueue_trial で追加されたパラメータに、Simplex の一番評価の悪い value 及び reflect 等で計算した value よりも良い value が存在した時に、既存の Simplex のパラメータ、reflect 等で計算したパラメータ、engueue_trial で追加されたパラメータの中からより良い dimension + 1 個のパラメータを選択して、Simplex を更新します。
  - _expand, _outside_contract, _inside_contract メソッドは、ruff のエラーの都合で _generator メソッドを短くするために分離したものです。
  - _generator メソッドでは、メインループ中に計算したパラメータと結果を past_vertices, past_values で記憶して、 _recontract_simplex メソッドで利用しています。
    - 各計算後に _recontract_simplex メソッドを追加しています。
- NelderMeadSampler
  - parallel_enabled 引数を追加しています。True の時に optuna.study.optimize による並列化が可能になります。
    - （手動で ask-tell を用いて並列化する際には False にしないとデッドロックが起きる可能性があるのが、少し複雑かもしれません）
    - before_trial メソッドでは、trial.system_attrs["fixed_params"] が存在する (enqueue_trial が発生している)場合には、NelderMeadAlgorism.get_vertex() は実行せずに、put_enqueue_vertex メソッドから帰ってきた param を計算に用います。
    - after_trial メソッドでは、通常の NelderMead から出力されたパラメータと、enqueue_trial で追加されたパラメータをそれぞれ個別に NelderMeadAlgorism の queue に put します。

2024-03-25 04:20 UTC, yoshipon commented
修正ありがとうございます．
あーcomplexityのエラー出ちゃうんですね．ここは分けると逆に可読性が下がると個人的には感じます．
noqaで無視しても良い気がするので，今日の打ち合わせで議論させて下さい．

enqueue_valueの扱いですが，例外で対応するのはどうでしょうか？
```python
while True:
    try:
        ...
        self.values[1:] = yield from self._waiting_for_list(len(self.vertices[1:]), self.values)
        ...
    except Enqueued as e:
        self.vertices, self.values = self.reconstract_simplex(
            self.vertices,
            self.values,
            e.enqued_vertices,
            e.enqued_values
        )
```
のようなものをイメージしています．
`waiting_for_XXX` メソッドの中で，単体の点より良い点が見つかったら例外を吐く実装です．
try-exceptの濫用でしょうか…？

2024-03-25 06:19 UTC, KanaiYuma-aist commented
開発者会議メモ
- ruff のエラー ( _generator is too complex )について
  - _generator に限り（計算のアルゴリズムを記述する箇所に限り）、ruff の （できれば complex のルールのみ）適用しないようにする。
    - 上記の方法を調べる必要あり？
    - 適用しない場合のルール作りも必要？（際限なく複雑化させていいわけでも無いため）
- enqueue_valueの扱い
  - simplex の最悪パラメータ、及び reflect 等で計算済みだが simplex に未反映のパラメータよりも良いパラメータが enqueue で入力された場合に、例外を投げる
    - 例外を投げる箇所はどこが適切？
  - try - except で例外をキャッチして、そこで recontract_simplex を行う。

2024-03-26 08:50 UTC, KanaiYuma-aist commented
try - except で例外をキャッチして、そこで recontract_simplex を呼び出すように改修しました。

d9c0b6be36301dd16e0138e169aabebe9af42e00

また、この改修で ruff のエラー ( _generator is too complex )は解消されたようです。
try - except を導入した分で if 文が減ったのが解消された理由のようです。
（これ以上なにか _generator に追加することがあれば、また発生しそうですが・・・）

2024-04-01 06:22 UTC, KanaiYuma-aist commented
開発者会議メモ
- ruff のエラーは try - except の実装でギリギリ回避可能な状態になったので、一旦保留とする。
  - 発生自体は _generator の行の末尾に `# noqa: C901` を追加することで、 _generator 内部でのみ ruff の too complex エラーを回避できる。
- 並列処理・enqueue_trial 関連のテストコードを書く。

2024-04-08 05:20 UTC, KanaiYuma-aist commented
開発者会議メモ
- テストコードの pytest への移行を行う
- value_queue, enqueue_vertex_queue, enqueue_value_queue の統合を行う（コードの確認？）
- enqueue_trial の処理を行う際は、すべてのパラメータが指定されている時のみ処理を行う
  - すべてのパラメータが指定されていない時は例外を出す
- nelder_mead でパラメータを出力できない時に、指定された他sampler？(randomやtpe)からパラメータを出力するオプションを追加する
  - そのパラメータは enqueue と同様に扱う（simplex のよりも良い結果が出たら、simplex を再構成する）

2024-04-09 05:29 UTC, KanaiYuma-aist commented
push して頂いたコードを元に並列処理・enqueue処理を正常に行えるように改修しました。

主な差分は下記コミットにまとまっています。
896d72ca73fbf52a0361c717f711d57ffad9d651

以下差分の補足です。

- NelderMeadAlgorism
  - 並列処理の initialize 時に results.get() を実行する回数が分からないと、デッドロックすることがあったので、self.num_enqueued を追加して results.get() の実行回数を明確にしました。
    - それに伴い、_waiting_for_results, _initialization の結果受け取りのループ回数に self.num_enqueued を追加しています。
  - raise UnexpectedVerticesUpdate を実行する条件を max(単体の values) > min(enqueue values) に変更しました。（暫定）
  - _initialization 内の処理を random vertices 生成 -> 計算結果の受け取り の処理順に変更しました。
    - 計算結果の受け取り -> 不足分の random vertices 生成 だと、ランダム値生成後に enqueue が発生した際に results に enqueue されたパラメータが残ってしまい、_initialization中に enqueue されたパラメータを処理できなくなります。
- その他軽微なtypoの修正(符号の向きや引数の順番等)

2024-04-09 09:17 UTC, yoshipon commented
pushありがとうございます．確認しました．めっちゃバグ埋め込んでましたね… すみません．

2024-04-10 05:06 UTC, yoshipon reviewed
ごめんなさい，バグと修正漏れが残っていたのでコメントします．

2024-04-10 05:06 UTC, yoshipon commented on aiaccel/hpo/algorithms/nelder_mead_algorithm.py
> +                vertex, value, enqueue = self.results.get(block=self.block)
ごめんなさい，下記抜けてました．
```suggestion
                vertex, value, enqueue = self.results.get(block=self.block, timeout=self.timeout)
```

2024-04-10 05:06 UTC, yoshipon commented on aiaccel/hpo/algorithms/nelder_mead_algorithm.py
> +        if len(self.values) == 0 or len(enqueued_values) > 0 and min(enqueued_values) < max(list(self.values)):
self.valuesはlistにしたので，list(...) 不要ですね．
```suggestion
        if len(self.values) == 0 or len(enqueued_values) > 0 and min(enqueued_values) < max(self.values):
```

2024-04-22 01:30 UTC, KanaiYuma-aist commented
sub_sampler 機能の sampler test を追加しました。

bb24195e78f79e1107dcef2d73eb6f47c8470b0b

2024-04-22 05:31 UTC, KanaiYuma-aist commented
開発者会議メモ
- sub_sampler 
  - sampler 内部で sub_sampler 用の study を呼んでいるが、これを sub_sampler の before_trial, sample_independent, after_trial を呼び出す形に改修する
- テスト関連
  - クラスにする必要が無い箇所を修正する
  - fixture 関連は共通している部分のみとして、部分的に利用している箇所は関数化もしくはクラス化する

2024-04-22 05:47 UTC, KanaiYuma-aist commented
@yoshipon 
次回の開発者会議が3週間後（恐らく5/13）とかなので、上記が終わった後にやることがあればコメントください。
（sampler のドキュメント作成とか？）

2024-04-22 06:05 UTC, KanaiYuma-aist commented
sub_sampler 用の study を sub_sampler の before_trial, sample_independent, after_trial に置き換える場合の懸念点
- before_trial, sample_independent, after_trial の引数に study が含まれているが、sub_sampler の before_trial 等を実行する際の引数 study は（study(sampler=sub_sampler) ではなく） nelder_mead_sampler で用いている study(sampler=nelder_mead_sampler) で問題無いか？
  - sampler の実装次第？

2024-04-23 08:26 UTC, KanaiYuma-aist commented
sub_study を削除して、sub_sampler の before_trial, sample_independent, after_trial を呼び出す形に改修しました。
懸念->https://github.com/aistairc/aiaccel/pull/346#issuecomment-2068558990

781c7a13581646a7da2babef2b1d4a4981179564

テストのクラスにする必要のない箇所のクラス削除、部分的にしか利用していない fixture の削除を行いました。

f56f429b0b1e986dc39d2a8f3d61626666fa3d61

2024-04-28 13:55 UTC, yoshipon requested changes
修正ありがとうございます．何点かコメントさせて頂きました．
これらを修正頂いた段階で，一旦このPRはマージできればと思います．

よろしくお願いします．

2024-04-28 13:55 UTC, yoshipon commented on tests/hpo/algorithms/test_nelder_mead_algorithm.py
> +            assert True
ここはこれ使うと良い気がします．
https://qiita.com/Jazuma/items/cb8dcd9ff01ed1c2d1f2

2024-04-28 13:55 UTC, yoshipon commented on tests/hpo/algorithms/test_nelder_mead_algorithm.py
> +        ([([-1.0, 0.0], None, False)]),
```suggestion
        [{"vertex": [-1.0, 0.0], "value": None, "enqueue": False}],
```
と書いた方が分かりやすいかも…？ お任せします．

2024-04-28 13:55 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                self.nm.put_value(params, np.inf)
```suggestion
            try:
                while True:
                    params = self.nm.get_vertex()

                    if all(low < x < high for x, (low, high) in zip(params, self._search_space.values(), strict=False)):
                        break

                    self.nm.put_value(params, np.inf)
            except NelderMeadEmptyError as e:
                if self.sub_sampler is None:
                    raise e
                else:
                    self.sub_sampler.before_trial(study, trial)
                    trial.set_user_attr("sub_trial", True)
```
こう書くとロジックがシンプルに見える気がしました．

2024-04-28 13:55 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            param_value = self.sub_sampler.sample_independent(study, trial, param_name, param_distribution)
```suggestion
        if "sub_trial" in trial.user_attrs:
            assert self.sub_sampler is not None
            param_value = self.sub_sampler.sample_independent(study, trial, param_name, param_distribution)
```
sub_trialが存在するとき，sub_samplerは存在する前提だと思うので，こう書いた方が意図が伝わりやすい気がしました．

2024-04-28 13:55 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            param_value = self.sub_sampler.sample_independent(study, trial, param_name, param_distribution)
ここって直にreturnするとダメなんでしたっけ？

2024-04-28 13:55 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            raise ValueError('trial.user_attrs["params"] is None')
これは存在する前提なので無くて良いような…？

2024-04-28 13:55 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +            )
良く分かっていないのですが，この確認って，before_trialでもやっているし，要らなくないですか？

2024-04-28 13:55 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                self.sub_sampler.after_trial(study, trial, state, values)
これちょっと思ったんですが，sub_samplerには，sub_trialでないものを全部enqueueしておいても良いかも…？

2024-04-28 13:55 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                self.sub_sampler.after_trial(study, trial, state, values)
sub_samplerにTPE指定したら強くなりそうじゃないですか？

2024-05-13 05:40 UTC, yoshipon approved these changes
ありがとうございました！

2024-05-13 05:41 UTC, merged