Add Job dispatcher
aistairc/aiaccel pull request #360
Opened 2024-03-11 01:30 UTC by aramoto99

`aiaccel/job/*` に，`ABCI` 向けのジョブディスパッチャを追加.

2024-03-25 05:03 UTC, yoshipon requested changes
PRありがとうございます！細かい部分ですが，コメントしたので反映お願いします．

2024-03-25 05:03 UTC, yoshipon commented on aiaccel/job/dispatcher.py
> +                self._submitted = True
```suggestion
            if self.stdout_file_path.exists() or self.stderr_file_path.exists():
                self._submitted = True
```
↑に関連して，型チェックを減らしたいですね．
ただ，この部分って，"r"だと判定できるだけで良いのではと思ったのですが，如何でしょうか．

2024-03-25 05:03 UTC, yoshipon commented on aiaccel/job/dispatcher.py
> +        return None
バッチで確認する機能の追加をお願いします．

2024-03-27 15:41 UTC, yoshipon requested changes
遅くなりすみません，細かく読みました．

2024-03-27 15:41 UTC, yoshipon commented on aiaccel/job/dispatcher.py
> +        if self._submitted and self.get_state() is None:
この部分ですが，submittedもstateの1つにすれば良いと思います．stateの一覧をEnumIntを使って作って貰えますか？
必要なのは，
```python
class JobStatus(EnumInt):
    UNSUBMITTED = 0
    WAITING = 1
    RUNNING = 2
    FINISHED = 3
```
あたりですかね．

2024-03-27 15:41 UTC, yoshipon commented on aiaccel/job/dispatcher.py
> +        return self._state
getterは書かずに，直接self.stateを参照するようにして下さい．
Pythonではprivate変数は無意味なので．

2024-03-27 15:41 UTC, yoshipon commented on aiaccel/job/dispatcher.py
> +        return self._state
stateは全ての状態を記述したenumにすれば optionalにせずによくなると思います．

2024-03-27 15:41 UTC, yoshipon commented on aiaccel/job/dispatcher.py
> +    @retry(_MAX_NUM=60, _DELAY=1.0)
retryは一旦消してください．retry.pyも同様です．バグの元な気がしています．

2024-03-27 15:41 UTC, yoshipon commented on aiaccel/job/dispatcher.py
> +            y = ast.literal_eval(y)
astは危険なように思います．
この部分は，コールバックとして実装を外に出すようにお願いします．

2024-03-27 15:41 UTC, yoshipon commented on aiaccel/job/dispatcher.py
> +            self.stderr_file_path.unlink()
```suggestion
```
ユーザが意図しない形でファイルが削除されるのは危険な気がします．
一旦この処理は削除お願いします．

2024-03-27 15:41 UTC, yoshipon commented on aiaccel/job/dispatcher.py
> +
これはrunの中にべた書きして下さい．

2024-03-27 15:41 UTC, yoshipon commented on aiaccel/job/dispatcher.py
> +        self._wait_for_job_submit_confirm()
他で呼ばれていないものは，全てここにべた書きして下さい．

2024-03-27 15:41 UTC, yoshipon commented on aiaccel/job/dispatcher.py
> +            raise ValueError(f"Job number not found: {self.job_name}")
この実装だと，aiaccel以外がジョブを投げると壊れてしまうと思います．
submit時に，`qsub` の標準出力をパースしてjob idを取得するようにして下さい．

2024-03-27 15:41 UTC, yoshipon commented on aiaccel/job/dispatcher.py
> +        return False
このクラスの実装として， `update_status()` を叩くと，qstatの実行結果から `self.status` を更新するように書いてください．
is_aliveやis_finishedを呼ぶたびにqstat叩く実装はABCIへの負荷をかけ過ぎるように思います．

2024-03-27 15:41 UTC, yoshipon commented on aiaccel/job/dispatcher.py
> +        if self._submitted and self.get_state() is None:
```python
if self.status > self.WAITING:
    ...
```
とか書けると何したいのか分かりやすくて良い気がしています．

2024-03-27 15:41 UTC, yoshipon commented on aiaccel/job/dispatcher.py
> +    stderr_file_path: Path | None = None
__init__で型が特定できるものは書かなくて良い気がしています．

2024-03-27 15:41 UTC, yoshipon commented on aiaccel/job/dispatcher.py
> +        cmd: str,
cmd不要と思うので削除下さい．

2024-03-27 15:41 UTC, yoshipon commented on aiaccel/job/dispatcher.py
> +        return job_numbers
qsubする時点でjob idを記録しておけば，本メソッドは不要に思います．

2024-03-27 15:46 UTC, yoshipon commented
今のコード拝見してて思ったんですが，ロジックはExecutorに全部うつして，AbciJobはデータ (dataclass) のみにした方が見通しが良いですかね…？

2024-04-20 09:06 UTC, yoshipon requested changes
PRありがとうございます！
機能追加のPRと，mypy.iniやactionsの設定のPRは，分けるようにお願いします．
また，今回頂いている変更箇所は，下記コメントの通り不要な修正になっておりますので，元に戻すようにお願いします．

2024-04-20 09:06 UTC, yoshipon commented on .github/workflows/lint.yaml
> +          pip install .[dev,dependencies,github-actions]
これdependencies要りましたっけ？ feature/v2-torchでは入れなくて動いているので，削除下さい．
```suggestion
          pip install .[dev,github-actions]
```

2024-04-20 09:06 UTC, yoshipon commented on mypy.ini
> +ignore_missing_imports = True
pyproject.tomlに必要なパッケージを追加して下さい．また，必要に応じてstubを書いてください．
こちらも，feature/v2-torch御覧頂ければと思います．
```suggestion
```

2024-04-21 10:52 UTC, yoshipon commented
お疲れ様です．少しコードを整理してみました．
実行結果はファイルに吐いた方が良いと思ったのですが，この部分はアプリ固有になるので，AbciJobに持たさない実装にしました．
使い方は，examples/job/optuna/main_{serial,parallel}.py をご覧下さい．

ABCI上でのテストはしていないので，正しく動作するかは不明です．テストの修正と合わせてご確認頂けると幸いです．

ロジック・構成はお送りしたコードを基本として頂きたいです．
修正が必要な点がありましたら，ミーティング (& 本ミーティング) で指摘頂けると幸いです．

2024-04-30 12:16 UTC, yoshipon requested changes
Pushありがとうございます．いくつか気になった部分があったので，ご対応頂けますと幸いです．
このmatch文カッコいいですね．

2024-04-30 12:16 UTC, yoshipon commented on aiaccel/job/abci_job_manager.py
> +            time.sleep(sleep_time)
この部分ですが，もとの意図は，「slotが空くまで待機，あいたらjobを返す」ですが，こちらは「jobが終了するまで待つ」に見えました．
もとの方が使いやすいと思うのですが，何か理由ありましたでしょうか？

2024-04-30 12:16 UTC, yoshipon commented on aiaccel/job/abci_job_manager.py
> +        self.finished_job_list: list[AbciJob] = []
`finished_job_list` は長時間使っていると溢れるので，削除願います．
本APIのユーザプログラム側で実装下さい．

2024-04-30 12:16 UTC, yoshipon commented on tests/job/_test_abci_job.py
> +}
ABCI上の実際のqstat結果 (匿名化したもの) をstrで保持して使って下さい．

2024-04-30 12:16 UTC, yoshipon commented on tests/job/_test_abci_job.py
> +}
多分，ファイルに書き出した方が良いと思います

2024-04-30 12:16 UTC, yoshipon commented on aiaccel/job/abci_job.py
> +            case "qw" | "h" | "t" | "s" | "S" | "T" | "Rq":
この書き方めっちゃカッコいいですね (感動)

2024-04-30 12:16 UTC, yoshipon commented on aiaccel/job/abci_job.py
> +        )  # (-> self.job_name: None回避)
意図了解です．stderrと同様に，1行で書けそうなら書いて頂けると嬉しいです．

2024-05-07 01:16 UTC, aramoto99 commented on aiaccel/job/abci_job_manager.py
> +            time.sleep(sleep_time)
すいません，sleepの記述箇所変更についてはデバッグ時の意図しない変更でしたので，修正いたします（元に戻します）

whileの条件式については，`self.available_slots() > 0` から `self.available_slots() == 0` に変更していますが，こちらは，空きスロット数が0の間待機するように変更したものであり，もとの意図に沿って改修しています．

2024-05-07 01:22 UTC, aramoto99 commented on aiaccel/job/abci_job_manager.py
> +        self.finished_job_list: list[AbciJob] = []
承知いたしました．終了ジョブを保持する処理は削除いたします．

2024-05-07 13:34 UTC, yoshipon commented on aiaccel/job/abci_job_manager.py
> +            time.sleep(sleep_time)
あばば。ボケてました。理解です。

2024-05-19 06:33 UTC, yoshipon requested changes
PRありがとうございます！ 何点かコメントしましたので、ご対応お願い致します。

2024-05-19 06:33 UTC, yoshipon commented on tests/job/test_abci_job.py
> +    stderr = ""
こちら、 runの返り値の型は、`subprocess.CompletedProcess` のようなので、こちらで作成下さい。

2024-05-19 06:33 UTC, yoshipon commented on tests/job/test_abci_job.py
> +    job_filename: str = "job.sh"
他の部分と合わせて、型推論に曖昧性がない部分の型ヒントは削除をお願いします。
コードが煩雑になってしまうので…

また、意味単位で適宜改行を入れて下さい。塊ごとに分かれている方が読みやすいと思います。

2024-05-19 06:33 UTC, yoshipon commented on tests/job/test_abci_job.py
> +    assert job.tag == job.tag
これらのassertはPathのもの以外は自明に真だと思いますので、確認お願いします。
Pathについては、assert isinstanceof(job.cwd, Path) と書くべきかと思います。

2024-05-19 06:33 UTC, yoshipon commented on tests/job/test_abci_job.py
> +    job_number = 123456
他の部分と合わせて、ジョブの状態を強制的に書き替える必要が無ければ、極力避けて頂けると幸いです。
実装が変わった際のコード変更の負担が大きくなってしまうように感じます。

本件、明日の打合せで方針すり合わせらると幸いです。

2024-05-19 06:33 UTC, yoshipon commented on tests/job/test_abci_job.py
> +    with pytest.raises(RuntimeError):
これだと、何のRuntimeErrorか分からないので、エラーメッセージの確認等入れた方が良いかと思いました。

2024-06-03 04:54 UTC, yoshipon commented on tests/job/test_abci_job.py
> +    job_filename: str = "job.sh"
こちら反映お願いします．

2024-06-19 05:06 UTC, aramoto99 commented
@ yoshipon
遅くなり申し訳ございません，Changes requested への対応，完了しました．

2024-06-19 09:37 UTC, yoshipon approved these changes
ありがとうございます！

2024-06-19 09:43 UTC, merged