Draft Implementation of CLI Command `start`
aistairc/aiaccel pull request #369
Opened 2024-05-31 08:00 UTC by aramoto99

- `examples/job/optuna` に `start.py` を作成
- 同階層に，configファイルのたたき台を作成

<hr>

使用方法:
```
python start.py objective.sh x1="[0, 10]" x2="[0, 10]" --config config.yaml
```

2024-06-03 04:56 UTC, yoshipon requested changes
PRありがとうございます．examplesの下でなく，aiaccel/appsのしたに作ってください．

2024-06-03 04:56 UTC, yoshipon commented on aiaccel/config/config.py
> +    seed: int | None
煩雑になるので，structured config使わなくて良い気がしています．

2024-06-03 04:58 UTC, yoshipon requested changes
PRありがとうございます．examplesの下でなく，aiaccel/appsのしたに作ってください．

2024-06-03 04:58 UTC, yoshipon commented on examples/job/optuna/start.py
> +    return getattr(module, attr_name)
hydra.utils.instantiate使って下さい．

2024-06-03 04:58 UTC, yoshipon commented on examples/job/optuna/start.py
> +    return params_dict
これもoc.from_cliで対処できると思います．

2024-06-03 04:58 UTC, yoshipon commented on examples/job/optuna/start.py
> +def execute_serially(filename: Path, config: DictConfig, params: dict[str, Any]) -> None:
serialとparallelはコード同一にできないでしょうか？

2024-06-05 14:38 UTC, yoshipon requested changes
PRありがとうございます！何点かコメントしました．ご確認お願いします．

2024-06-05 14:38 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +    parser.add_argument("params", nargs="*", help='Additional parameters in the form of key="value"')
こちら不要で良いと思います．

2024-06-05 14:38 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +    config = oc.load(args.config)
これでどうでしょう？
```suggestion
    args, unk_args = parser.parse_known_args()
    config = oc.merge(
        oc.load(args.config),
        oc.from_cli(unk_args)
    }
```

2024-06-05 14:38 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +                hparams[key] = trial.suggest_float(key, *value)
この部分ですが，suggestする部分をルーチンとして切り出して貰っても良いでしょうか？
config.yamlには
```
params:
    _target_: aiaccel.apps.optimize.suggest_hparams
```
みたいなのを書いてinstantiateするようにしましょう．

2024-06-05 14:38 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +
これ必要でしたっけ？
```suggestion
```

2024-06-06 06:45 UTC, aramoto99 commented on aiaccel/apps/optimize.py
> +                hparams[key] = trial.suggest_float(key, *value)
configにparamsを書くならば,他にも色々指定出来たほうが良いかも？と思いましたが，いかがでしょうか？

例：
```
params:
  x1:
    _target_: optuna.trial.Trial.suggest_float
    name: x1
    low: 0.0
    high: 1.0
    log: false
  x2:
    _target_: optuna.trial.Trial.suggest_float
    name: x2
    low: 0.0
    high: 1.0
    log: false
```

2024-06-10 05:24 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +                hparams[key] = trial.suggest_float(key, *value)
```
params:
  _target_: hoge
  x1:
    _target_: optuna.trial.Trial.suggest_float
    low: 0.0
    high: 1.0
    log: false
  x2:
    _target_: opthuna.trial.Trial.suggest_float
    low: 0.0
    high: 1.0
    log: false
```

2024-06-10 05:26 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +                hparams[key] = trial.suggest_float(key, *value)
```
def __init__(self, **kwargs):
    for key, val in kwargs.items():
        if isinstance(key, list):
            ...
```

2024-06-11 06:36 UTC, aramoto99 commented on aiaccel/apps/optimize.py
> +                hparams[key] = trial.suggest_float(key, *value)
[cf75cd8](https://github.com/aistairc/aiaccel/pull/369/commits/cf75cd8011308416be1fd2ab91261e2141cbb473) にて上記の変更を行いました. お手数ですですがご確認いただきたく，よろしくお願いいたします．

2024-06-13 13:42 UTC, yoshipon requested changes
PRありがとうございます！
下記気になったところコメントしてみました．ご確認お願いします．

2024-06-26 11:21 UTC, yoshipon requested changes
更新ありがとうございます！

2024-06-26 11:21 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +                self.params[name] = lambda trial, name=name, low=low, high=high: trial.suggest_float(name, low, high)
こちらでいかがでしょう？
```suggestion
                param = SuggestFloat(name, low, high)
```

2024-06-26 11:21 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +                self.params[name] = param
```suggestion
            self.params[name] = param
```

2024-06-26 11:21 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +    def __init__(self, **params_def: dict[str, float]) -> None:
```suggestion
    def __init__(self, **params_def: dict[str, tuple[float, float] | SuggestFloat]) -> None:
```

2024-06-26 11:21 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +                hparams[param_name] = hp_generator
先日の意図は，ここを簡略化したい，ということだったので，constantを詰めたい場合は，別途constant用のgenerator書くのが正しい気がします．
```suggestion
        return {name: param_fn(trial) for name, param_fn in self.params.items()}
```

2024-06-26 11:21 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +    step: float | None | None = None
型アノテーションご注意下さい．

2024-07-01 05:12 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +                    param = lambda trial, name=name, low=low, high=high: SuggestFloat(name, low, high)(trial)  # type: ignore # noqa: E731
こうで良い気がします？
```suggestion
                    param = SuggestFloat(name, low, high)
```

2024-07-01 05:16 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +class Suggest:
Genericsで定義して貰えると嬉しいです🙇‍♂️

2024-07-01 05:21 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +    parser.add_argument("job_filename", type=str, help="The shell script to execute.")
こうすると，↓でPathしなくて良さそう．
```suggestion
    parser.add_argument("job_filename", type=Path, help="The shell script to execute.")
```

2024-07-22 05:31 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +class SuggestFloat(Generic[T]):
```suggestion
class SuggestFloat(Suggest[float]):
```
こう？

2024-07-29 05:29 UTC, yoshipon approved these changes
ありがとうございます！

2024-07-30 00:44 UTC, merged