local mode
aistairc/aiaccel pull request #378
Opened 2024-07-18 07:46 UTC by aramoto99

ローカル実行用のモジュールを作成。

- 実行方法
`python -m aiaccel.apps.local.optimizer --config ...`

2024-08-21 16:45 UTC, yoshipon requested changes
PRありがとうございます。下記コメントしましたので、ご確認・修正お願いします。
併せて、wrapper.pyのファイル名について、何のwrapperか分かる命名をお願いできますと幸いです。

よろしくお願いします。

2024-08-21 16:45 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +    jobs: AbciJobExecutor | LocalJobExecutor | None = None
ここの型アノテーションは、共通のベースクラスを作って | でなく1個だけ書いた方が良いと思います。

2024-08-21 16:45 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +            if hasattr(job, "tag"):
jobにtagが無い場合がどういう場合か教えて下さい。

2024-08-21 16:45 UTC, yoshipon commented on aiaccel/job/local_job_manager.py
> +class LocalJobExecutor:
機能的にABCIJobと被ってる部分も多いと思いますので、切り出せる部分は共通クラス化お願いします。

2024-08-21 16:45 UTC, yoshipon commented on aiaccel/job/local_job_manager.py
> +        future.tag = tag  # type: ignore
これはちょっと行儀が悪いので、避けた方がよいですね… 
futureをくるんだjobクラス作るのはどうでしょうか。二度手間ですかね？

2024-08-22 01:12 UTC, aramoto99 commented on aiaccel/apps/optimize.py
> +            if hasattr(job, "tag"):
ここの意図ですが、mypyのエラー回避です
future が tag を持っていないためです

2024-08-22 01:18 UTC, aramoto99 commented
ファイル名ですが、ひとまず `suggest_wrapper.py` としておきます
 
> wrapper.pyのファイル名について、何のwrapperか分かる命名

2024-08-22 03:47 UTC, aramoto99 commented on aiaccel/job/local_job_manager.py
> +        future.tag = tag  # type: ignore
ひとまず、JobFuture という名前で future の wrapper クラスを作成いたします

2024-08-22 03:54 UTC, aramoto99 commented on aiaccel/apps/optimize.py
> +            if hasattr(job, "tag"):
追記：JobFuture( futureの wrapper)を作成し、mypyエラー回避のための分岐が不要になりましたので現在のコミットでは ` if hasattr(job, "tag"):...`は削除しています

2024-08-26 19:04 UTC, yoshipon requested changes
ご対応ありがとうございます。Abciとlocalで共通化できそうなところが何か所か気になったので、ご確認・ご対応お願いできますと幸いです。

2024-08-26 19:04 UTC, yoshipon commented on aiaccel/job/base_job_executor.py
> +        job_name: str | None = None,
この辺はbaseでなくabci特有な気がします！

2024-08-26 19:04 UTC, yoshipon commented on aiaccel/job/local_job_executor.py
> +        return self.n_max_jobs - len(self.job_list)
ほぼ同じコードがABCIの方にもあるので、設計を整理頂いて共通化した方が良いかと思います。

2024-08-26 19:04 UTC, yoshipon commented on aiaccel/job/local_job_executor.py
> +                still_running.append(job_future)
この部分も同様に、共通化できる気がします。

2024-09-19 19:15 UTC, yoshipon requested changes
修正ありがとうございます。下記の対応お願いします。

2024-09-19 19:15 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +    jobs: BaseJobExecutor | None = None
```suggestion
    jobs: BaseJobExecutor
```

2024-09-19 19:15 UTC, yoshipon commented on aiaccel/job/local_job_executor.py
> +class JobFuture:
これは `LocalJob` として基底クラスを継承下さい。

2024-09-19 19:15 UTC, yoshipon commented on aiaccel/job/local_job_executor.py
> +        raise RuntimeError(error_msg) from e
他から使われていないように見えますが如何でしょうか。
```suggestion
```

2024-09-19 19:15 UTC, yoshipon commented on aiaccel/job/local_job_executor.py
> +        return self.status
これも基底クラスに。

2024-09-19 19:15 UTC, yoshipon commented on aiaccel/job/local_job_executor.py
> +        JobFuture.update_status_batch(self.job_list)
これも上手く抽象化して基底クラスに入れられますか？

2024-09-25 08:35 UTC, aramoto99 commented on aiaccel/job/local_job_executor.py
> +        JobFuture.update_status_batch(self.job_list)
- `LocalJob.update_status_batch(self.job_list)`
- `AbciJob.update_status_batch(self.job_list)`

各環境のJobクラスのclassmethodを参照するので、纏めないほうがいいかも？と思い、とりあえずそのままにしています。

2024-09-27 08:10 UTC, aramoto99 commented on aiaccel/job/local_job_executor.py
> +        JobFuture.update_status_batch(self.job_list)
@yoshipon 変更が完了しましたので、ご確認いただきたく、よろしくお願いいたします

2024-09-27 08:10 UTC, aramoto99 commented
@yoshipon 変更が完了しましたので、ご確認いただきたく、よろしくお願いいたします

2024-10-01 00:14 UTC, aramoto99 commented on aiaccel/job/local_job_executor.py
> +        return self.status
base_job.py へ移動

https://github.com/aistairc/aiaccel/blob/2b8d0f039b33865d71db5018352df3336d777b16/aiaccel/job/base_job.py#L24-L33

2024-10-01 00:17 UTC, aramoto99 commented on aiaccel/job/local_job_executor.py
> +        raise RuntimeError(error_msg) from e
LocalJobExecutorのメンバ関数に変更

https://github.com/aistairc/aiaccel/blob/2b8d0f039b33865d71db5018352df3336d777b16/aiaccel/job/local_job_executor.py#L79-L92

2024-10-01 00:19 UTC, aramoto99 commented on aiaccel/job/local_job_executor.py
> +class JobFuture:
BaseJobを継承するLocalJobへ変更。

また、local_job_executor.pyからlocal_job.py（新規作成）へ変更

https://github.com/aistairc/aiaccel/blob/2b8d0f039b33865d71db5018352df3336d777b16/aiaccel/job/local_job.py#L1-L39

2024-10-01 00:20 UTC, aramoto99 commented on aiaccel/apps/optimize.py
> +    jobs: BaseJobExecutor | None = None
https://github.com/aistairc/aiaccel/blob/2b8d0f039b33865d71db5018352df3336d777b16/aiaccel/apps/optimize.py#L77-L79

2024-10-01 00:52 UTC, yoshipon commented on aiaccel/job/local_job_executor.py
> +        JobFuture.update_status_batch(self.job_list)
こちらですが、対象のJobクラスをクラス変数にすることで纏められないでしょうか？ あんまPythonicではないですかね？

2024-10-01 19:45 UTC, yoshipon approved these changes
下記の反映もお願いします🙇

2024-10-01 19:45 UTC, yoshipon commented on aiaccel/job/job_status.py
> +            raise ValueError(f"Unexpected status: {status}")
これは、local_job.pyとの対称性を考えると、abci_job.py内に実装すべきではないでしょうか？
コード全体の構造化を意識して頂くと良いと思います！

2024-10-01 19:46 UTC, yoshipon requested changes
すみません、間違ってApproveしてしまいました。

2024-10-07 06:54 UTC, aramoto99 commented
@yoshipon  下記の変更点についてレビューいただきたく、よろしくお願いいたします。

- hogeJobExecutor での jobClass の指定方法を、次のように変更。
    - AbciJobExecutor
        ~~~ python
        class AbciJobExecutor(BaseJobExecutor):
            JobClass = AbciJob
        ~~~
    - LocalJobExecutor
        ~~~ python
        class LocalJobExecutor(BaseJobExecutor):
            JobClass = LocalJob
        ~~~
        
- from_qsubをAbciJobへ移管.

2024-10-18 04:29 UTC, yoshipon requested changes
遅くなってしまいすみません、こちらのみ対応お願い致します。

2024-10-18 04:29 UTC, yoshipon commented on aiaccel/job/abci_job.py
> +                raise ValueError(f"Unexpected status: {status}")
この書き方だと、ABCIJobがfrom_qsubで生成されるように見える気がします。
from_qsubはここでしか使っていないので、LocalJobと同じくべた書きして貰っても良いですか？

2024-10-21 04:34 UTC, yoshipon approved these changes
ありがとうございます！

2024-10-21 04:35 UTC, merged