Normalization of search_space in NelderMeadAlgorithm
aistairc/aiaccel pull request #382
Opened 2024-08-16 06:28 UTC by KanaiYuma-aist

- NelderMeadAlgorithm 内で search_space を正規化して扱うように変更しました
  - NelderMeadAlgorithm の引数を search_space から、次元数を扱う dimension に変更しました
  - 探索範囲外を弾く(結果をinf扱いにする)処理は NelderMeadAlgorithm 内で行うように改修しました
  - NelderMeadSampler 内に、正規化表現と本来の search_space とを相互変換する処理を追加しました
- それら変更に伴い、テストコードを改修しました

2024-08-16 15:15 UTC, yoshipon requested changes
ありがとうございます！ いくつかコメントしました。
ご確認・ご対応お願いします。

2024-08-16 15:15 UTC, yoshipon commented on aiaccel/hpo/algorithms/nelder_mead_algorithm.py
> +                if all(normalize_range[0] < x < normalize_range[1] for x in vertex):
現状でグローバル変数による固定であれば、ハードコードで良いように思います。
```suggestion
                if all(0 <= x <= 1 for x in vertex):
```

2024-08-16 15:15 UTC, yoshipon commented on aiaccel/hpo/algorithms/nelder_mead_algorithm.py
> +        lows, highs = zip(*self._search_space, strict=False)
ここも0 ~ 1なので、149行目に0, 1でハードコードすると良いかと。

2024-08-16 15:15 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                )
こう書いた方が読みやすいように思います。
```suggestion
                iter_ = zip(self.nm.get_vertex(), self._search_space.values(), strict=False)
                params = np.array([(high - low) * value + low for value, (low, high) in iter_])
```

2024-08-16 15:15 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                ),
↑と同じものが2回でてくるので、これはプライベートメソッド化すると良いと思います。

2024-08-19 05:49 UTC, KanaiYuma-aist commented on aiaccel/hpo/algorithms/nelder_mead_algorithm.py
> +                if all(normalize_range[0] < x < normalize_range[1] for x in vertex):
対応しました

7023efb0e417ee3ee4f9ba60a5b663d6b6351ec6

2024-08-19 05:49 UTC, KanaiYuma-aist commented on aiaccel/hpo/algorithms/nelder_mead_algorithm.py
> +        lows, highs = zip(*self._search_space, strict=False)
対応しました

7023efb0e417ee3ee4f9ba60a5b663d6b6351ec6

2024-08-19 05:58 UTC, KanaiYuma-aist commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                ),
探索空間 -> 正規化 の変換処理と、正規化 -> 探索空間 の変換処理はそれぞれ1箇所ずつありますが、
探索空間 -> 正規化 を2回行っている箇所は無いと思っています。

2024-08-20 16:04 UTC, yoshipon commented on aiaccel/hpo/samplers/nelder_mead_sampler.py
> +                ),
なるほどです。ありがとうございます。

2024-08-20 16:04 UTC, yoshipon commented
dimension -> dimensionsにしたのと、__init__で指定しなくても動くようにしてみました。ご確認お願いします。

2024-08-26 18:57 UTC, yoshipon requested changes
ありがとうございます。下記一点のみ修正お願いします。

2024-08-26 18:57 UTC, yoshipon commented on aiaccel/hpo/optuna/samplers/nelder_mead_sampler.py
> +                ),
長くなってしまうので、iterator分けましょう。
```suggestion
            it = zip(trial.params.values(), self._search_space.values(), strict=False)
            ...
                np.array([(value - low) / (high - low) for value, (low, high) in it]),
```

2024-08-27 01:26 UTC, yoshipon commented on aiaccel/hpo/algorithms/nelder_mead_algorithm.py
> +            )
ここも？

```suggestion
            if self.dimensions + 1 > **len(self.vertices):
                num_random_points = self.dimensions + 1 - len(self.vertices)
            else:
                num_random_points = 0
```

2024-09-19 19:23 UTC, yoshipon requested changes

2024-09-19 19:23 UTC, yoshipon commented on aiaccel/hpo/algorithms/nelder_mead_algorithm.py
> +            raise ValueError("vertex is None.")
何故 `None` なのかが分からんので、ヒントとなるような文言を追記下さい。

2024-09-20 05:14 UTC, KanaiYuma-aist commented on aiaccel/hpo/algorithms/nelder_mead_algorithm.py
> +            raise ValueError("vertex is None.")
こちらは上記 if 文が無かった場合に、 mypy で下記エラーが出るため、その回避のために入れた if 文ですね。

```
$ mypy --config-file mypy.ini .
aiaccel/hpo/algorithms/nelder_mead_algorithm.py:144:16: error: Incompatible return value type (got "ndarray[Any, dtype[floating[_64Bit]]] | None", expected "ndarray[Any, dtype[floating[_64Bit]]]")  [return-value]  
Found 1 error in 1 file (checked 26 source files)
```

vertex = None の場合は直前の処理でエラーになるはずなので、実際にこの if 文を通過することは無いと思われます。

https://github.com/aistairc/aiaccel/blob/6caa8eb3f20faf2658921c1701eb645787e2b57d/aiaccel/hpo/algorithms/nelder_mead_algorithm.py#L130-L139

2024-09-24 01:25 UTC, yoshipon commented on aiaccel/hpo/algorithms/nelder_mead_algorithm.py
> +            raise ValueError("vertex is None.")
ありがとうございます！

2024-10-01 19:40 UTC, yoshipon approved these changes
修正ありがとうございました！

2024-10-01 19:40 UTC, merged