Support for NelderMeadSampler resumption.
aistairc/aiaccel pull request #387
Opened 2024-09-18 06:18 UTC by KanaiYuma-aist

- NelderMeadSampler の再開時の処理を追加しました
  - 初回実行か再開実行かを判別するために num_trial で内部で trial 数をカウントしています。 num_trial よりも optuna 側の trial 数が進んでいる場合、再開実行と判定して _resumption を呼び出します
  - _resumption では空回し処理を行っており、NelderMeadAlgorithm 内のイテレータ及び simplex を同様の状態に戻しています。
    - この部分の処理時間は 10000 trial の再開処理を行った場合でも数秒程度だったので、途中から空回しする等の処理を行う必要性は薄いと判断します。
    - pickle 化などを用いたシリアライズ処理は、NelderMeadAlgorithm 内のイテレータを pickle 化することが不可能だったので、断念しました。
  - storage を指定した場合(再開機能を利用する場合)、trial.set_user_attr で各種情報を記憶する方式だと after_trial 内部でそれらの情報が参照できない仕様になっていたため、代わりに study._storage.set_trial_system_attr で記憶する方式に変更しました。
- 再開テストを追加しました

2024-09-19 19:39 UTC, yoshipon requested changes
PRありがとうございます！
似たロジックを複数個所に書くのは、保守性下げるので避けた方が良いと思います。

Algorithm側をpickle可能に改修する方向は如何でしょうか。
たとえば、
`_generator`にflag引数を付けて、reflect, expand, ... のどこから始めるかを指定するとか。

2024-09-19 19:39 UTC, yoshipon commented on aiaccel/hpo/optuna/samplers/nelder_mead_sampler.py
> +                        self.sub_sampler.before_trial(study, trial)
この部分

2024-09-20 04:40 UTC, KanaiYuma-aist commented
コメントありがとうございます。

> Algorithm側をpickle可能に改修する方向は如何でしょうか。
> たとえば、
> _generatorにflag引数を付けて、reflect, expand, ... のどこから始めるかを指定するとか。

これは _generator を、現行の yield を用いたイテレータ方式の実装から、全く別の実装にするという認識でよろしいでしょうか？

2024-09-20 05:29 UTC, yoshipon commented
すみません言語化出来てなくて申し訳ないんですが、こういう感じの何かで、どこから処理始めるか・どこまで処理を終えたかを指定・保存できないかなと。
```python
    def _generator(self, start_from: Status | None = None) -> Generator[npt.NDArray[np.float64] | None, None, None]:  # noqa: C901
        # initialization
        lows, highs = zip(*self._search_space.values(), strict=False)

        self.vertices, self.values = self._collect_enqueued_results()

        try:
            num_random_points = self.simplex_size - len(self.vertices) if self.simplex_size > len(self.vertices) else 0
            random_vertices = list(self._rng.uniform(lows, highs, (num_random_points, len(self._search_space))))
            yield from random_vertices

            random_vertices, random_values = yield from self._wait_for_results(num_random_points)

            self.vertices = self.vertices + random_vertices
            self.values = self.values + random_values
        except UnexpectedVerticesUpdateError as e:
            self.vertices, self.values = e.updated_vertices, e.updated_values

        # main loop
        shrink_requied = False
        while True:
            try:
                # sort self.vertices by their self.values
                order = np.argsort(self.values)[: self.simplex_size]
                self.vertices = [self.vertices[idx] for idx in order]
                self.values = [self.values[idx] for idx in order]

                if start_from >= Status.Reflect:
                    # reflect
                    yc = np.mean(self.vertices[:-1], axis=0)
                    yield (yr := yc + self.coeff.r * (yc - self.vertices[-1]))

                    fr = yield from self._wait_for_result()

                    if self.values[0] <= fr < self.values[-2]:
                        self.vertices[-1], self.values[-1] = yr, fr

                elif fr < self.values[0] and start_from >= Status.Expand:  # expand
                    ...
                    self.status = Status.Expand
                elif self.values[-2] <= fr < self.values[-1] and start_from >= Status.OutContract:  # outside contract
                    ...
                    self.status = Status.OutContract
                elif self.values[-1] <= fr and start_from >= Status.InContract:  # inside contract
                    ...
                    self.status = Status.InContract
```

2024-09-24 06:59 UTC, KanaiYuma-aist commented
上記の形式にすると、当初の _generator の設計方針だった可読性が落ちそうですが、よろしいですか？
（よくある流れ図？の形とは一見異なる形状のコードになる
　Initialize や shrink の途中から再開させるための処理がやや面倒そう）

2024-10-04 05:28 UTC, KanaiYuma-aist commented
NelderMeadAlgorism の pickle 化の懸念点

results (queue.Queue) が pickle 化不可(正確には queue の内部で用いられている threading 関連変数が pickle 化不可)
__getstate__ で results を削除(del) することで pickle 化回避は可能だが、 queue に put された数値ごと消えてしまうため、
特に initialize や shrink の途中から再開した際にエラー落ちしてしまう
queue.Queue 内部の threading 関連変数を削除すれば、 put された数値を維持したまま pickle 化できるが、 queue.Queue 内部を直接触るのはあまり好ましくなさそう(保守が面倒そう)
queue.Queue の代わりに collections.deque を用いれば、pickle 化可能になる見込みだが、スレッドセーフを自力で担保する必要がある？

2024-10-09 08:04 UTC, KanaiYuma-aist commented
開発者会議内にて、空回しによる再開機能の実装の方がoptunaの仕様に合っているという結論が出たので、
空回しによる再開機能の実装・最新ブランチへの対応を行いました。

2024-10-18 04:32 UTC, yoshipon approved these changes
ありがとうございます！

2024-10-18 04:33 UTC, merged