add load_if_exists
aistairc/aiaccel pull request #395
Opened 2024-10-29 06:02 UTC by aramoto99

2024-10-29 06:10 UTC, aramoto99 commented
本commitの差分の以下二つは本件の改修とは無関係ですが、以前の変更時の消し忘れのファイルのため今回で削除しております。
- examples/job/optuna/main_paralell.py
- examples/job/optuna/main_serial.py

2024-10-30 07:00 UTC, aramoto99 commented
@yoshipon 
実行コマンドに`--resume` を付加することで再開できるように変更しました。
例: `python -m aiaccel.apps.optimize objective.sh --config config.yaml --resume`

2024-11-04 11:51 UTC, yoshipon requested changes

2024-11-04 11:51 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +        with open_dict(config):
open_dictって必要ですか？ なくても書き込めるような…

2024-11-04 11:51 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +            config.study.load_if_exists = args.resume
```suggestion
    if args.resume:
        config.study.load_if_exists = True
```

2024-11-05 00:59 UTC, aramoto99 commented on aiaccel/apps/optimize.py
> +        with open_dict(config):
ありがとうございます、修正しました

2024-11-05 01:47 UTC, yoshipon approved these changes

2024-11-05 04:06 UTC, merged