Add docs for NelderMeadSampler
aistairc/aiaccel pull request #397
Opened 2024-10-30 06:45 UTC by KanaiYuma-aist

- NelderMeadSampler のドキュメントを追加しました。

2024-11-04 11:44 UTC, yoshipon requested changes
ありがとうございます．
こちらですが，docstringから動的生成するなど可能でしょうか．
また明日相談させて下さい．

2024-11-08 07:09 UTC, KanaiYuma-aist commented
aiaccelhpo/... -> docs/hpo/... のようにディレクトリ構造をコピーしつつドキュメントを自動生成する方法が見つからなかったので、暫定で v1 に習って api_reference ディレクトリ内に自動生成したドキュメントを配置しました

2024-11-11 03:15 UTC, yoshipon commented
ありがとうございます！
こちらですが， `develop/v2` にPRできるよう修正願えますか？ (docsに必要な機能をこちらにマージして頂きたいです)
一旦，日本語対応部分は落として作成下さい．

3.gitignoreに追記頂きたいのと，GH Actions時にgh-pagesブランチには出力頂く形にして貰えると嬉しいです．

2024-11-13 08:25 UTC, KanaiYuma-aist commented
- docstring から日本語部分を削除しました。
- .gitignore に docs/source/api_reference を追記しました
- publish_pages.yaml を追加しました（main ブランチからの流用）
  - 現状の設定では main にマージされたら、 gh-pages が更新されるようになっているようです

2024-11-15 05:15 UTC, KanaiYuma-aist commented
html のテーマ一覧がこちらにありました

https://sphinx-themes.org/#theme-sphinx-book-theme

ただ、いくつかそのまま使おうとしてもビルド時にエラーが出でビルドが止まってしまう（+エラー文で調べても何も出てこない・・・）ものが混じっています
ひとまず、PyData が仰っていた pytorch 等のドキュメントスタイルに近そうです。
https://sphinx-themes.org/sample-sites/pydata-sphinx-theme/#

2024-11-18 02:20 UTC, KanaiYuma-aist commented
ビルド時のコマンドを以下に記載します。

```
cd aiaccel/
sphinx-apidoc -f -o ./docs/source/api_reference/ ./aiaccel/
cd docs/
make html
```

(上記実行後、 aiaccel/docs/build/html/index.html をブラウザで開きます。)

2024-11-27 12:42 UTC, yoshipon commented
ありがとうございます．下記ご対応お願いします．

この部分の削除をお願いします．多分他のフォーマット用の何かかと思います．
![image](https://github.com/user-attachments/assets/1d4ef84d-534d-40f1-85e1-7c35eec954d8)

API referenceの一覧表示では，メソッドは隠すようにお願いします．長いととっつき辛いので．
![image](https://github.com/user-attachments/assets/5f7ea607-7939-43ff-b937-0d5a0c3b9b29)

あと，ロゴのサイズですが，バーの高さに対して少し大きく感じます．これがテーマのデフォルトであればこのままで良いですが，修正可能でしたら90%くらいのサイズだとベターかと思います．

本当は全体的に構成を見直したいですが，ちょっと時間がかかりそうなので，木曜日の夕方以降にご連絡します．

2024-11-28 05:45 UTC, KanaiYuma-aist commented
- ページ上部に表示されていた aiaccel Documentation を削除しました
  - docs/source/_templates/breadcrumbs.html で表示されていた様子だったので、一旦全文削除しました
- 自動生成ドキュメントの maxdepth: を 2 にするオプションを追加しました
  - これで表示される深さが 2 になるので、モジュールは表示されなくなりました
- ロゴの表示サイズ変更については調査中です

2024-12-03 08:32 UTC, KanaiYuma-aist commented
- ドキュメントの構成を Overview, Installation, User Guide, API Reference, Contribution Guide に変更しました
  - User Guide, Contribution Guide 用のディレクトリを追加、hpo.optimize torch.train のプレースホルダを作成しました
- API Reference の構成を cypy のものを参考に改修しました

2024-12-05 08:40 UTC, KanaiYuma-aist commented
- docs/source/api_reference/*.md を削除しました。
- contribution_guide を統合、user_guide を hpo.optimize torch.train で分割しました。
- htmp_sidebar の設定に 'sourcelink.html' を追加しました。
  - これで、API Reference 参照中はいつでもサイドバーに API Reference の内容が表示されます。

2024-12-06 04:31 UTC, yoshipon requested changes
修正ありがとうございます．下記取り急ぎご対応下さい．
反映頂き次第マージ致します．

2024-12-06 04:31 UTC, yoshipon commented on aiaccel/hpo/algorithms/nelder_mead_algorithm.py
>              value: float: Calculation result 計算結果
```suggestion
            vertex: npt.NDArray[np.float64]: Parameters
            value: float: Calculation result
```

2024-12-06 04:31 UTC, yoshipon commented on docs/image/logo_aiaccel_re_edit.png
ファイル名の修正をお願いします．logo_aiaccel_padding.png 等の中身が分かる体でお願いします．あと余白ですが，可能なら，今の倍つけて頂けると幸いです．

2024-12-06 04:31 UTC, yoshipon commented on docs/index.html
このファイル必要でしょうか？

2024-12-06 04:31 UTC, yoshipon commented on docs/source/hpo/optuna/sampler/neldermeadsampler_en.md
この中身って今どこかから参照されていますか？ もし否であれば，docstringとマージした方が良いと思います．

2024-12-06 04:31 UTC, yoshipon commented on docs/source/hpo/optuna/sampler/samplers.rst
こちら多分不要ですかね？

2024-12-06 04:31 UTC, yoshipon commented on docs/source/_templates/breadcrumbs.html
このファイルも不要であれば削除願います．

2024-12-06 04:31 UTC, yoshipon commented on docs/source/index.rst
> +* The TPE algorithm implementation uses Optuna.
```suggestion
* Part of this work was developed under a commissioned project of the New Energy and Industrial Technology Development Organization (NEDO).
```

2024-12-06 06:43 UTC, KanaiYuma-aist commented on docs/image/logo_aiaccel_re_edit.png
対応しました。

6ec9e4d22a621cd10c33095142c5e700c3f88062

2024-12-06 06:45 UTC, KanaiYuma-aist commented on docs/source/hpo/optuna/sampler/neldermeadsampler_en.md
NelderMeadSampler の docstring と統合しました。

b42bd7f2c0112f872d4ab1224981220ea0e7f34e

サンプルコードの表示のため、sphinx.ext.doctest を追加しました

63b3be48016ba10af7e384e85c8da911db90a81a

2024-12-06 06:46 UTC, KanaiYuma-aist commented on docs/index.html
対応しました。

f6db2808121564523751e6d2f2a4ff20ddff92c4

2024-12-06 06:46 UTC, KanaiYuma-aist commented on docs/source/hpo/optuna/sampler/samplers.rst
対応しました。

f6db2808121564523751e6d2f2a4ff20ddff92c4

2024-12-06 06:46 UTC, KanaiYuma-aist commented on docs/source/_templates/breadcrumbs.html
対応しました。

f6db2808121564523751e6d2f2a4ff20ddff92c4

2024-12-06 06:49 UTC, yoshipon approved these changes
ご対応ありがとうございました！

2024-12-06 06:50 UTC, merged