add partial fix mode
aistairc/aiaccel pull request #398
Opened 2024-11-11 01:15 UTC by aramoto99

一度最適化を実行したのち、指定のパラメータを固定してresumeする実行モードを追加.

- 使用方法
実行時にコマンドライン引数に `--fix パラメータ名` で固定するパラメータを指定する。
（固定する値は前回実行時の最良値）

- 例:
    ``` bash
    python -m aiaccel.apps.optimize objective.sh --config config.yaml --fix x2
    ```

2024-11-11 03:11 UTC, yoshipon requested changes
ありがとうございます！ 確認しました．

2024-11-11 03:11 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +    return fixed_params
1か所のみでしか使われていないので，本文にべた書き下さい．
if args.fix がmain内で見えないとロジックが不透明だと思います．

2024-11-11 04:24 UTC, aramoto99 commented on aiaccel/apps/optimize.py
> +    return fixed_params
↑の内容を反映しました。お手数ですが再度レビュ頂きたく、よろしくお願いいたします。

2024-11-12 00:45 UTC, yoshipon requested changes
ありがとうございます．確認しました．
修正お願い致します．

2024-11-12 00:45 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +        )
下の111行からのところもそうですが，この手のは上手く，
```
prev_study = optuna.load_study(
    storage=...,
    study_name=config.study.study_name,
)
```
のように書けないでしょうか？
インスタンス化するものが自明な場合は，instantiateは避けた方が無難と思います．

2024-11-12 00:45 UTC, yoshipon commented on aiaccel/apps/optimize.py
>              "engine_kwargs": {"connect_args": {"timeout": 30}},
このtimeoutの設定は必要でしょうか？ 不要であれば，
`sqlite:///optuna.db` だけで十分かと思います．

2024-11-12 00:45 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +    config.study.setdefault("study_name", "aiaccel_study")
こちらの方がロジック見えやすくて良いかと思いますが，いかがですか？
```suggestion
    if "study_name" not in config.study:
        config.study.study_name = "aiaccel_study"
```

2024-11-12 00:45 UTC, yoshipon commented on aiaccel/apps/optimize.py
>              "_target_": "optuna.storages.RDBStorage",
これだとデフォルトでRDBに書き込む設定になってしまうと思うんですが，その分遅くならないでしょうか？

2024-11-12 00:45 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +
これはOptuinaに機能が実装されているので，そちらをコールするように書いて貰えると嬉しいです．

2024-11-14 03:13 UTC, aramoto99 commented on aiaccel/apps/optimize.py
>              "_target_": "optuna.storages.RDBStorage",
resumeすることを前提として作成しましたが、不要でしたら削除いたします。

config に storage 関連の記述がない場合は dbを使用しない = resume は不可

2024-11-14 06:56 UTC, aramoto99 commented on aiaccel/apps/optimize.py
> +    config.study.setdefault("study_name", "aiaccel_study")
その記述へ変更後、 complexity が上がって `ruff check` でエラーが出るようになってしまいましたが、ひとまず可読性を優先してその記述へ変更し、 `noqa: C901` で`optimize.py` の `main()` はこのチェックを無視するようにしています。

将来的に、ruff での complexity に関するチェックは除外してもいいかもです。

2024-11-14 07:01 UTC, aramoto99 commented on aiaccel/apps/optimize.py
>              "_target_": "optuna.storages.RDBStorage",
ひとまず、configに storageの記述がない場合は、

``` json
"storage",
{
    "_target_": "optuna.storages.InMemoryStorage",
},
```

が設定されるように変更。経過をメモリに保存するので resume は不可。resumeが必要な場合はconfigでユーザーが設定する。

2024-11-14 07:02 UTC, aramoto99 commented on aiaccel/apps/optimize.py
> +
探してみたのですが、結果を印字する関数がoptunaにはなさそうでしたので、ひとまず削除しておきます

2024-11-18 00:59 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +
```
study._log_completed_trial(frozen_trial)
```
こちら使って下さい．

2024-11-18 01:00 UTC, yoshipon commented on aiaccel/apps/optimize.py
>              "_target_": "optuna.storages.RDBStorage",
resumeは引数1つで実施できるのに，非対称だと思います．何かコマンドラインオプションを作るなど対応お願いします．

2024-11-21 07:55 UTC, aramoto99 commented on aiaccel/apps/optimize.py
> +        )
```
prev_study = instantiate(
    {
        "_target_": "optuna.load_study",
        "storage": config.study.storage,
        "study_name": config.study.study_name,
    }
)
```

この箇所は、storageをinstantiateで生成してload_study()をコールするように変更しました。


study, storage, samplerなどの生成に関してですが、例えばTPESamplerやPartialFixedSamplerなど各オプションのパターンに対応する分岐処理を書く必要があり、かえってコードが複雑になってしまうと考え、これらはinstantiateの使用が適切ではと思いましたが、いかがでしょうか？（optunaの仕様変更のたびにaiacceを変更するのは、従来のコンセプトからすこし外れるかも）

2024-11-27 12:21 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +# while maintaining logical cohesion of the study configuration setup process.
削除下さい．

2024-11-27 12:27 UTC, yoshipon requested changes
作業ありがとうございます．
下記コメント致しました．ご確認お願いします．

2024-11-27 12:27 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +            config.study.storage = default_storage
この部分ですがロジックを整理できますか？
幾つかの機能・処理を纏めて書いてしまっているように見えました．

2024-11-27 12:27 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +                }
samplerの定義がないときはfixed_paramsにならないように見えましたが，その実装で大丈夫でしょうか．

2024-11-27 12:27 UTC, yoshipon commented on aiaccel/apps/optimize.py
> +            )
すみません，純粋な質問なのですが，この部分tellではダメでしょうか．

2024-11-29 08:21 UTC, aramoto99 commented on aiaccel/apps/optimize.py
> +                }
ありがとうございます。以下のように変更いたしました。

~~~ python
if fixed_params:
    base_sampler = config.study.sampler if "sampler" in config.study else default_sampler
    config.study.sampler = {
        "_target_": "optuna.samplers.PartialFixedSampler",
        "fixed_params": fixed_params,
        "base_sampler": base_sampler,
    }
~~~

2024-11-29 08:23 UTC, aramoto99 commented on aiaccel/apps/optimize.py
> +            )
ありがとうございます。以下のように変更いたしました。

~~~ python
frozen_trial = study.tell(trial=trial, values=y, state=TrialState.COMPLETE)
study._log_completed_trial(frozen_trial)
~~~

2025-01-05 12:43 UTC, closed without merging