Resolved warnings during document generation.
aistairc/aiaccel pull request #408
Opened 2024-12-18 01:32 UTC by KanaiYuma-aist

ドキュメント生成時に発生していた各種警告文を解消しました。

2025-01-05 13:21 UTC, yoshipon requested changes

2025-01-05 13:21 UTC, yoshipon commented on .github/workflows/publish_pages.yaml
> +          sphinx-apidoc --maxdepth 2 -f -o ./docs/source/api_reference/ -s inc ./aiaccel/
ありがとうございます．こちらですが，workaroundの類なので，あとから意図が分かるよう参照した記事のリンクをコメントで追記下さい．
また，incで名前が良いのか不安です．incが何の略か分かっていないのですが，慣例でしょうか？ あまり例がなければ，例えば，*.rst_ にするなど，実態を分かり易くした方が良いかなと思いました．ご検討お願いします．

2025-01-06 05:02 UTC, KanaiYuma-aist commented on .github/workflows/publish_pages.yaml
> +          sphinx-apidoc --maxdepth 2 -f -o ./docs/source/api_reference/ -s inc ./aiaccel/
開発者会議メモ
- 拡張子を変更する warning 回避策は削除して、それで表示される警告文に関してはそのままにしておく

2025-01-06 07:07 UTC, KanaiYuma-aist commented on .github/workflows/publish_pages.yaml
> +          sphinx-apidoc --maxdepth 2 -f -o ./docs/source/api_reference/ -s inc ./aiaccel/
対応しました

2025-01-27 01:34 UTC, yoshipon approved these changes
ありがとうございます！

2025-01-27 01:34 UTC, merged