Add  `session.close()` in aiaccel/storage/*
aistairc/aiaccel pull request #47
Opened 2022-08-31 00:05 UTC by aramoto99

Added a process to close the database.

2022-08-31 02:22 UTC, yoshipon commented
Thank you for the PR!
Is it really needed? Can't we utilize destructors?

2022-08-31 02:23 UTC, yoshipon requested changes
Thank you for the PR!
Is this really needed? Can't we utilize destructors?

2022-09-02 08:39 UTC, aramoto99 commented
- changed the position of call to cimmit() so that it will EXCEPT when an error occurs in commit().

- Added close() function.

2022-09-05 04:12 UTC, yoshipon approved these changes

2022-09-05 04:13 UTC, merged