Feature/refactoring resume
aistairc/aiaccel pull request #88
Opened 2022-10-12 07:31 UTC by aramoto99

シリアライズするデータの定義箇所を変更しました．
これまでは，`aiaccel/util/serialize.py`で全てのシリアライズするデータの情報(ラベル名)を登録していました．
この仕様では，ユーザが新規でoptimizerを追加するとき，`aiaccel/util/serialize.py`の変更が必要になる状況が発生し得ます．<br>
それはaiaccelのコンセプトとは異なります．仕様を変更し，master, optimizer, schedulerの __init__()でシリアライズするデータを登録するように変更しました．

- シリアライズデータの登録
~~~ python 
storage.variable.register(process_name, ['hoge', 'foo'])
~~~

- 保存
~~~ python
storage.variable.d['hoge'].set(trial_id, value)
~~~

- 読み出し
~~~ python
storage.variable.d['hoge'].get(trial_id)
~~~

---
aiaccel/util/serialize.pyの機能は，`aiaccel/storage/variable.py`へ移管しました．
(DBを使う機能であるため，他のDB処理と同じ階層へ．もともと`util`内にシリアライズ処理がありましたが，それはファイルシステム版の名残)

---
上記変更に合わせて，テストケースを変更しました．

2022-10-13 08:03 UTC, aramoto99 commented
*_Optimizerにて，_serialize(), _deserialize()の記述が不要になるように変更しました．

2022-10-13 08:11 UTC, yoshipon requested changes
爆速でありがとうございます！
随分すっきりして良くなったように思います。

各XxxxOptimizerにある `self._serialize(self.trial_id.integer)` ですが、みんな `generate_parameter` メソッドの最後に呼んでいる気がします。
共通のコードはAbstractOptimizerに括りだしてください。
https://github.com/aistairc/aiaccel/blob/5577a167fd53cafe7af401f9fc92b0771b23d248/aiaccel/optimizer/abstract_optimizer.py#L209
この辺に書けば良いかと。

あと、何箇所かコメントアウトしたまま消されていないコードブロックが見受けられますので、削除もお願いします。

よろしくお願いします。

2022-10-13 08:37 UTC, aramoto99 commented
generate_parameterのループ処理内(パラメータ生成毎)にserializeをする必要(*1)があるため，纏めるならばループ内の最終処理のregister_ready()内部で_serialize()をすると都合が良いのですが，いかがでしょうか...．
(「生成パラメータをDBに登録してシリアライズ実行」なので，文脈的にも違和感は無いかと)

(*1 パラメータ生成毎にシリアライズしないと，再開機能を使用したときに内部情報の整合性が合わなくなる状況があります．）

https://github.com/aistairc/aiaccel/blob/5577a167fd53cafe7af401f9fc92b0771b23d248/aiaccel/optimizer/abstract_optimizer.py#L92

2022-10-14 00:45 UTC, yoshipon approved these changes
ありがとうございます！

2022-10-14 00:45 UTC, merged