Fix Issue #58
aistairc/aiaccel pull request #90
Opened 2022-10-14 01:54 UTC by aramoto99

util/terminal.pyを削除し，printに置換えました．

2022-10-14 03:12 UTC, yoshipon commented
ありがとうございます！ 
printの部分ってloggingにできますか？ 前回のmtgで特段の理由なければloggingに統一という話だったように思います。

# このPRの1番最初のメッセージの冒頭に、"Closes #58" と書いておいて貰えますか？ Issueと対応づけられればと思います。

2022-10-14 03:12 UTC, yoshipon approved these changes
ありがとうございます！
printの部分ってloggingにできますか？ 前回のmtgで特段の理由なければloggingに統一という話だったように思います。

\# このPRの1番最初のメッセージの冒頭に、"Closes https://github.com/aistairc/aiaccel/issues/58" と書いておいて貰えますか？ Issueと対応づけられればと思います。

2022-10-14 03:13 UTC, yoshipon requested changes
ありがとうございます！
printの部分ってloggingにできますか？ 前回のmtgで特段の理由なければloggingに統一という話だったように思います。

\# このPRの1番最初のメッセージの冒頭に、"Closes https://github.com/aistairc/aiaccel/issues/58" と書いておいて貰えますか？ Issueと対応づけられればと思います。

2022-10-18 01:50 UTC, yoshipon requested changes

2022-10-18 04:53 UTC, aramoto99 commented on aiaccel/cli/report.py
> +logger.addHandler(StreamHandler())
loggingでメッセージを標準出力に流す場合，
~~~ python
logger.addHandler(StreamHandler())
~~~
が必要という風に認識しております．
デフォルトではできなさそうです..

2022-10-18 04:56 UTC, yoshipon commented on aiaccel/cli/report.py
> +logger.addHandler(StreamHandler())
あざます。デフォルトだと、infoとdebugは標準出力で、それ以外は標準エラー出力っぽいです。不要な気がします。
またloglevelは放っておけば勝手に環境変数読んでくれると思います。

https://techblog.sasashima.works/archives/229

2022-10-23 09:02 UTC, yoshipon approved these changes

2022-10-23 09:02 UTC, merged